// ============================================================================
// Localized names/descriptions for content (characters, parts, items...).
// Merged into the main dictionary by i18n.js - content keeps its strings
// next to its data. Every key has EN + IT (verified by tests).
// ============================================================================

export const CONTENT_STRINGS = {
  // ---------------- characters ----------------
  'char.ember': { en: 'Ember', it: 'Ember' },
  'char.ember.species': { en: 'the Dustfox', it: 'la Volpe delle Sabbie' },
  'char.ember.personality': { en: 'Balanced daredevil with fire in her tail', it: 'Temeraria equilibrata con il fuoco nella coda' },
  'char.cinder': { en: 'Cinder', it: 'Cinder' },
  'char.cinder.species': { en: 'the Magmabear', it: 'l\u2019Orso di Magma' },
  'char.cinder.personality': { en: 'Heavyweight bruiser, first into every brawl', it: 'Peso massimo aggressivo, sempre primo nella mischia' },
  'char.zephyr': { en: 'Zephyr', it: 'Zephyr' },
  'char.zephyr.species': { en: 'the Windheron', it: 'l\u2019Airone del Vento' },
  'char.zephyr.personality': { en: 'Feather-light and quick off the line', it: 'Leggero come una piuma, scatto bruciante' },
  'char.bastion': { en: 'Bastion', it: 'Bastion' },
  'char.bastion.species': { en: 'the Ironshell', it: 'il Guscio di Ferro' },
  'char.bastion.personality': { en: 'Unmovable wall, shrugs off every hit', it: 'Muro inamovibile, ignora ogni colpo' },
  'char.nova': { en: 'Nova', it: 'Nova' },
  'char.nova.species': { en: 'the Starlynx', it: 'la Lince Stellare' },
  'char.nova.personality': { en: 'Chases pure top speed, fragile but fast', it: 'Insegue la velocit\u00e0 pura, fragile ma velocissima' },
  'char.thistle': { en: 'Thistle', it: 'Thistle' },
  'char.thistle.species': { en: 'the Bramblehop', it: 'il Salto di Rovo' },
  'char.thistle.personality': { en: 'Twitchy corner dancer, impossible to box out', it: 'Danzatore di curve, impossibile da chiudere' },
  'char.coral': { en: 'Coral', it: 'Coral' },
  'char.coral.species': { en: 'the Tidedrake', it: 'il Drago delle Maree' },
  'char.coral.personality': { en: 'At home on any surface, wet or wild', it: 'A suo agio su ogni superficie, bagnata o selvaggia' },
  'char.volt': { en: 'Volt', it: 'Volt' },
  'char.volt.species': { en: 'the Stormkit', it: 'il Cucciolo della Tempesta' },
  'char.volt.personality': { en: 'Explodes off the start, never stops buzzing', it: 'Esplode alla partenza, non smette mai di vibrare' },
  'char.obsidian': { en: 'Obsidian', it: 'Obsidian' },
  'char.obsidian.species': { en: 'the Ashwing', it: 'l\u2019Ala di Cenere' },
  'char.obsidian.personality': { en: 'Drift artist from the dark side of the caldera', it: 'Artista della derapata dal lato buio del cratere' },
  'char.juniper': { en: 'Juniper', it: 'Juniper' },
  'char.juniper.species': { en: 'the Mosscat', it: 'il Gatto di Muschio' },
  'char.juniper.personality': { en: 'Forest wanderer, treats dirt like tarmac', it: 'Nomade della foresta, tratta lo sterrato come asfalto' },
  'char.ratchet': { en: 'Ratchet', it: 'Ratchet' },
  'char.ratchet.species': { en: 'the Scraprat', it: 'il Ratto di Rottami' },
  'char.ratchet.personality': { en: 'Grease-stained tinkerer with a heavy wrench', it: 'Meccanico unto con una chiave pesante' },
  'char.lumi': { en: 'Lumi', it: 'Lumi' },
  'char.lumi.species': { en: 'the Frostowl', it: 'il Gufo di Gelo' },
  'char.lumi.personality': { en: 'Calm, precise, slices corners like ice', it: 'Calmo, preciso, taglia le curve come ghiaccio' },
  'char.aurelia': { en: 'Aurelia', it: 'Aurelia' },
  'char.aurelia.species': { en: 'the Sundancer', it: 'la Danzatrice del Sole' },
  'char.aurelia.personality': { en: 'Golden champion of the Crown Circuit', it: 'Campionessa dorata del Circuito della Corona' },
  'char.umbra': { en: 'Umbra', it: 'Umbra' },
  'char.umbra.species': { en: 'the Voidmole', it: 'la Talpa del Vuoto' },
  'char.umbra.personality': { en: 'Digs through shortcuts nobody else can see', it: 'Scava scorciatoie che nessun altro riesce a vedere' },
  'unlock.aurelia': { en: 'Win the Crown Cup', it: 'Vinci la Coppa Corona' },
  'unlock.umbra': { en: 'Complete the Night Shift achievement', it: 'Completa l\u2019impresa Turno di Notte' },

  // ---------------- chassis ----------------
  'chassis.duneBlazer': { en: 'Dune Blazer MK-1', it: 'Dune Blazer MK-1' },
  'chassis.duneBlazer.desc': { en: 'The trusty all-rounder from the Sunforge garage.', it: 'L\u2019affidabile tuttofare dell\u2019officina Sunforge.' },
  'chassis.featherwing': { en: 'Featherwing', it: 'Ala di Piuma' },
  'chassis.featherwing.desc': { en: 'So light it leaps. Gives up top speed for zip.', it: 'Cos\u00ec leggero che vola. Rinuncia alla velocit\u00e0 per lo scatto.' },
  'chassis.ironcladHauler': { en: 'Ironclad Hauler', it: 'Corazzato da Traino' },
  'chassis.ironcladHauler.desc': { en: 'A rolling fortress. Slow to wake, hard to stop.', it: 'Una fortezza su ruote. Lento a svegliarsi, difficile da fermare.' },
  'chassis.tempestBolt': { en: 'Tempest Bolt', it: 'Fulmine Tempesta' },
  'chassis.tempestBolt.desc': { en: 'Built for screaming straights. Nervous in corners.', it: 'Fatto per rettilinei urlanti. Nervoso in curva.' },
  'chassis.bumblewisp': { en: 'Bumblewisp', it: 'Soffio di Calabrone' },
  'chassis.bumblewisp.desc': { en: 'A corner-hugging honeybee. Slower on the open road.', it: 'Un\u2019ape che abbraccia le curve. Pi\u00f9 lento sul dritto.' },
  'chassis.rockjaw': { en: 'Rockjaw', it: 'Mascella di Roccia' },
  'chassis.rockjaw.desc': { en: 'Eats rough terrain for breakfast. Heavy and blunt.', it: 'Divora terreni accidentati a colazione. Pesante e diretto.' },
  'chassis.cometCourier': { en: 'Comet Courier', it: 'Corriere Cometa' },
  'chassis.cometCourier.desc': { en: 'Launches like a comet, slides wide if you blink.', it: 'Parte come una cometa, allarga la traiettoria se sbatti le palpebre.' },
  'chassis.gearworkRoyale': { en: 'Gearwork Royale', it: 'Ingranaggio Reale' },
  'chassis.gearworkRoyale.desc': { en: 'Ancient gear-tech tuned for silky drifts.', it: 'Antica tecnologia a ingranaggi per derapate setose.' },

  // ---------------- wheels ----------------
  'wheel.standard': { en: 'Standard Treads', it: 'Cingoli Standard' },
  'wheel.slimline': { en: 'Slimline Racers', it: 'Cerchi Filanti' },
  'wheel.duneRollers': { en: 'Dune Rollers', it: 'Rulli delle Dune' },
  'wheel.gyroRings': { en: 'Gyro Rings', it: 'Anelli Giroscopici' },
  'wheel.ironDrums': { en: 'Iron Drums', it: 'Tamburi di Ferro' },
  'wheel.slickComets': { en: 'Slick Comets', it: 'Comete Slick' },
  'wheel.stormSpikes': { en: 'Storm Spikes', it: 'Punte della Tempesta' },
  'wheel.chromeHalos': { en: 'Chrome Halos', it: 'Aure Cromate' },
  'wheel.mossGrippers': { en: 'Moss Grippers', it: 'Aderenti di Muschio' },
  'wheel.turboSprockets': { en: 'Turbo Sprockets', it: 'Ruote Dentate Turbo' },
  'wheel.balloonFloaters': { en: 'Balloon Floaters', it: 'Palloni Galleggianti' },
  'wheel.rallyHex': { en: 'Rally Hex', it: 'Esagonali da Rally' },

  // ---------------- cosmetics ----------------
  'paint.sunsetOrange': { en: 'Sunset Orange', it: 'Arancio Tramonto' },
  'paint.duneTeal': { en: 'Dune Teal', it: 'Verde Acqua Duna' },
  'paint.emberRed': { en: 'Ember Red', it: 'Rosso Brace' },
  'paint.canyonCream': { en: 'Canyon Cream', it: 'Crema del Canyon' },
  'paint.nightInk': { en: 'Night Ink', it: 'Inchiostro Notturno' },
  'paint.forestMoss': { en: 'Forest Moss', it: 'Muschio di Foresta' },
  'paint.royalViolet': { en: 'Royal Violet', it: 'Viola Reale' },
  'paint.stormYellow': { en: 'Storm Yellow', it: 'Giallo Tempesta' },
  'paint.glacierBlue': { en: 'Glacier Blue', it: 'Blu Ghiacciaio' },
  'paint.magmaBlack': { en: 'Magma Black', it: 'Nero Magma' },
  'paint.coralPink': { en: 'Coral Pink', it: 'Rosa Corallo' },
  'paint.bronzeGear': { en: 'Bronze Gear', it: 'Bronzo Ingranaggio' },
  'paint.silverMist': { en: 'Silver Mist', it: 'Nebbia d\u2019Argento' },
  'paint.goldForge': { en: 'Gold Forge', it: 'Oro della Forgia' },
  'paint.prismPearl': { en: 'Prism Pearl', it: 'Perla Prisma' },
  'paint.voidChrome': { en: 'Void Chrome', it: 'Cromo del Vuoto' },

  'decal.none': { en: 'Clean', it: 'Pulito' },
  'decal.racingStripe': { en: 'Racing Stripe', it: 'Striscia da Corsa' },
  'decal.sunEmblem': { en: 'Sun Emblem', it: 'Emblema Solare' },
  'decal.gearStamp': { en: 'Gear Stamp', it: 'Stampo a Ingranaggio' },
  'decal.flameTrail': { en: 'Flame Trail', it: 'Scia di Fiamme' },
  'decal.stormBolt': { en: 'Storm Bolt', it: 'Fulmine Tempesta' },
  'decal.waveCrest': { en: 'Wave Crest', it: 'Cresta d\u2019Onda' },
  'decal.starField': { en: 'Star Field', it: 'Campo Stellato' },

  'exhaust.twinPipes': { en: 'Twin Pipes', it: 'Doppio Scarico' },
  'exhaust.stackVents': { en: 'Stack Vents', it: 'Sfiati Verticali' },
  'exhaust.quadBurst': { en: 'Quad Burst', it: 'Quadruplo Scoppio' },
  'exhaust.turbineRing': { en: 'Turbine Ring', it: 'Anello Turbina' },

  'effect.classicFlame': { en: 'Classic Flame', it: 'Fiamma Classica' },
  'effect.emberTrail': { en: 'Ember Trail', it: 'Scia di Braci' },
  'effect.frostWake': { en: 'Frost Wake', it: 'Scia Gelata' },
  'effect.venomSpark': { en: 'Venom Spark', it: 'Scintilla Velenosa' },
  'effect.voidShimmer': { en: 'Void Shimmer', it: 'Bagliore del Vuoto' },

  // ---------------- items: the Sunforge arsenal (22 originals) ----------------
  'item.cinderLance': { en: 'Cinder Lance', it: 'Lancia di Brace' },
  'item.cinderLance.desc': { en: 'A straight spear of fire that punches through one kart and keeps going.', it: 'Una lancia di fuoco dritta che trapassa un kart e prosegue.' },
  'item.cinderLance.counter': { en: 'It does not steer - move off its line.', it: 'Non sterza: spostati dalla sua traiettoria.' },
  'item.hornetPod': { en: 'Hornet Pod', it: 'Vespaio d\u2019Ottone' },
  'item.hornetPod.desc': { en: 'Three weak homing wasps in a spread; each one only nudges you.', it: 'Tre vespe a ricerca, deboli e in ventaglio; ognuna ti d\u00e0 solo una spinta.' },
  'item.hornetPod.counter': { en: 'They turn slowly - break left or right early.', it: 'Curvano lentamente: scarta a destra o a sinistra in anticipo.' },
  'item.glassFang': { en: 'Glass Fang', it: 'Zanna di Vetro' },
  'item.glassFang.desc': { en: 'Locks onto the kart ahead and shatters where it lands, leaving glass on the road.', it: 'Aggancia il kart davanti e si frantuma dove colpisce, lasciando vetro sulla strada.' },
  'item.glassFang.counter': { en: 'Drift to break the lock, then avoid the patch.', it: 'Derapata per rompere l\u2019aggancio, poi evita la chiazza.' },
  'item.kilnMortar': { en: 'Kiln Mortar', it: 'Mortaio della Fornace' },
  'item.kilnMortar.desc': { en: 'Lobs a shell at where the kart ahead is going to be, not where it is.', it: 'Lancia una bomba dove il kart davanti sta per arrivare, non dove si trova.' },
  'item.kilnMortar.counter': { en: 'The landing ring is the warning - drive out of it.', it: 'L\u2019anello di impatto \u00e8 l\u2019avviso: esci dal cerchio.' },
  'item.slagMine': { en: 'Slag Mine', it: 'Mina di Scoria' },
  'item.slagMine.desc': { en: 'A crucible that drags karts in, then erupts and launches whatever it is holding.', it: 'Un crogiolo che attira i kart, poi erutta e lancia in aria ci\u00f2 che trattiene.' },
  'item.slagMine.counter': { en: 'Give it a wide berth - it arms in under a second.', it: 'Tieniti largo: si arma in meno di un secondo.' },
  'item.brassBulwark': { en: 'Brass Bulwark', it: 'Baluardo d\u2019Ottone' },
  'item.brassBulwark.desc': { en: 'A solid gate across half the road that stops karts dead and shoves them back.', it: 'Un cancello solido che sbarra mezza strada, blocca i kart e li respinge.' },
  'item.brassBulwark.counter': { en: 'Pick the open side early - and it blocks its owner too.', it: 'Scegli presto il lato libero: blocca anche chi lo piazza.' },
  'item.dustVeil': { en: 'Dust Veil', it: 'Velo di Polvere' },
  'item.dustVeil.desc': { en: 'A curtain of desert dust. No damage, just no grip and no visibility.', it: 'Una tenda di polvere del deserto. Nessun danno, solo niente aderenza e niente visibilit\u00e0.' },
  'item.dustVeil.counter': { en: 'Ease off the throttle and hold it straight through.', it: 'Alleggerisci l\u2019acceleratore e tieni dritto finch\u00e9 non ne esci.' },
  'item.thornScatter': { en: 'Thorn Scatter', it: 'Spine a Ventaglio' },
  'item.thornScatter.desc': { en: 'Three iron thorns flung into a fan behind you, closing off the inside line.', it: 'Tre spine di ferro lanciate a ventaglio dietro di te: chiudono la linea interna.' },
  'item.thornScatter.counter': { en: 'Small targets - take the wide line around them.', it: 'Bersagli piccoli: passa dalla linea esterna.' },
  'item.sunflare': { en: 'Sunflare', it: 'Vampa Solare' },
  'item.sunflare.desc': { en: 'An instant full boost wrapped in a moment of immunity.', it: 'Un boost massimo istantaneo, avvolto in un attimo di immunit\u00e0.' },
  'item.sunflare.counter': { en: 'The immunity is shorter than the boost - do not dive into it.', it: 'L\u2019immunit\u00e0 dura meno del boost: non tuffartici contro.' },
  'item.emberDraft': { en: 'Ember Draft', it: 'Corrente di Brace' },
  'item.emberDraft.desc': { en: 'A long, strong pull of speed - paid for with the drift button.', it: 'Una spinta lunga e potente, pagata col pulsante della derapata.' },
  'item.emberDraft.counter': { en: 'Save it for the straights.', it: 'Conservalo per i rettilinei.' },
  'item.glasswalk': { en: 'Glasswalk', it: 'Passo di Vetro' },
  'item.glasswalk.desc': { en: 'Turn to glass: untouchable, unable to act, and shedding a trail that slows whoever follows.', it: 'Diventi vetro: intoccabile, incapace di agire, e lasci una scia che rallenta chi insegue.' },
  'item.glasswalk.counter': { en: 'Nothing can hit you - but you cannot hit back.', it: 'Niente pu\u00f2 colpirti, ma tu non puoi colpire.' },
  'item.duneSkip': { en: 'Dune Skip', it: 'Salto della Duna' },
  'item.duneSkip.desc': { en: 'A hop that lifts you clean off the ground and throws you forward.', it: 'Un balzo che ti stacca da terra e ti lancia in avanti.' },
  'item.duneSkip.counter': { en: 'Little steering in the air - aim before you jump.', it: 'Poco sterzo in aria: mira prima di saltare.' },
  'item.rustBlight': { en: 'Rust Blight', it: 'Morbo di Ruggine' },
  'item.rustBlight.desc': { en: 'Rust in the drivetrain of the kart ahead: top speed is fine, acceleration is not.', it: 'Ruggine nella trasmissione del kart davanti: la velocit\u00e0 massima regge, l\u2019accelerazione no.' },
  'item.rustBlight.counter': { en: 'Forge Ward or Echo Bell cleanses it.', it: 'Sigillo della Fornace o Campana d\u2019Eco lo rimuovono.' },
  'item.gyroJinx': { en: 'Gyro Jinx', it: 'Maleficio Giroscopico' },
  'item.gyroJinx.desc': { en: 'Spins a rival\u2019s gyros: a full, uncontrollable rotation that also dumps their item.', it: 'Fa impazzire i giroscopi di un rivale: una rotazione completa e incontrollabile che gli fa cadere l\u2019oggetto.' },
  'item.gyroJinx.counter': { en: 'A Hex Mirror sends it straight back.', it: 'Uno Specchio Esagonale lo rimanda indietro.' },
  'item.hourglassHex': { en: 'Hourglass Hex', it: 'Sortilegio della Clessidra' },
  'item.hourglassHex.desc': { en: 'Hangs a slow bubble on a rival - it travels with them and catches anyone drafting past.', it: 'Appendi a un rivale una bolla rallentante: viaggia con lui e cattura chi gli passa in scia.' },
  'item.hourglassHex.counter': { en: 'It expires on its own - leave the bubble or wait it out.', it: 'Scade da solo: esci dalla bolla o aspetta che finisca.' },
  'item.hexMirror': { en: 'Hex Mirror', it: 'Specchio Esagonale' },
  'item.hexMirror.desc': { en: 'Paints a sigil on your kart: the next hostile item lands on whoever threw it.', it: 'Dipingi un sigillo sul kart: il prossimo oggetto ostile colpisce chi lo ha lanciato.' },
  'item.hexMirror.counter': { en: 'One use, and it expires - bait it with something cheap.', it: 'Un solo uso, e scade: attiralo con qualcosa di poco valore.' },
  'item.forgeWard': { en: 'Forge Ward', it: 'Sigillo della Fornace' },
  'item.forgeWard.desc': { en: 'A quenched plate that eats the next hit and scours off whatever is already on you.', it: 'Una piastra temprata che assorbe il prossimo colpo e ripulisce ci\u00f2 che hai gi\u00e0 addosso.' },
  'item.forgeWard.counter': { en: 'One charge only.', it: 'Una sola carica.' },
  'item.echoBell': { en: 'Echo Bell', it: 'Campana d\u2019Eco' },
  'item.echoBell.desc': { en: 'A ringing shockwave: cleanses you, shatters every trap in range and pays charge back.', it: 'Un\u2019onda sonora: ti ripulisce, frantuma ogni trappola nel raggio e ti restituisce carica.' },
  'item.echoBell.counter': { en: 'Radius-limited - ring it while the traps are close.', it: 'Raggio limitato: suonala quando le trappole sono vicine.' },
  'item.mirageDecoy': { en: 'Mirage Decoy', it: 'Esca Miraggio' },
  'item.mirageDecoy.desc': { en: 'A heat-haze double behind you: projectiles go for it, and it flashes over whoever is near.', it: 'Un doppio di calura dietro di te: i proiettili lo cercano e abbaglia chi gli \u00e8 vicino.' },
  'item.mirageDecoy.counter': { en: 'It shimmers - the real kart does not.', it: 'Tremola: il kart vero no.' },
  'item.stormCell': { en: 'Storm Cell', it: 'Cella Temporalesca' },
  'item.stormCell.desc': { en: 'Bolts a charged cell to your exhaust. Every drift-boost you release arcs backwards, three times.', it: 'Fissi una cella carica allo scarico. Ogni boost in derapata si scarica all\u2019indietro, tre volte.' },
  'item.stormCell.counter': { en: 'Stay out of the cone behind them, or make them spend the charges.', it: 'Resta fuori dal cono dietro di loro, oppure fagli spendere le cariche.' },
  'item.kilnLottery': { en: 'Kiln Lottery', it: 'Lotteria della Fornace' },
  'item.kilnLottery.desc': { en: 'Throw your item back into the kiln and take whatever comes out, weighted by position.', it: 'Ributta l\u2019oggetto nella fornace e prendi ci\u00f2 che esce, pesato sulla tua posizione.' },
  'item.kilnLottery.counter': { en: 'It can come out worse. That is the price.', it: 'Pu\u00f2 uscire qualcosa di peggio. \u00c8 il prezzo.' },
  'item.sunforgeHeart': { en: 'Sunforge Heart', it: 'Cuore della Forgia' },
  'item.sunforgeHeart.desc': { en: 'A violent burst that trails molten fire behind it. Only the back of the field ever finds one.', it: 'Un\u2019esplosione violenta che si trascina dietro fuoco fuso. Solo gli ultimi in classifica la trovano.' },
  'item.sunforgeHeart.counter': { en: 'Do not sit in its wake - it burns.', it: 'Non restare nella sua scia: brucia.' },

  // ---------------- HUD / race (new) ----------------
  'hud.item': { en: 'ITEM', it: 'OGGETTO' },
  'hud.itemHint': { en: 'Press E to use', it: 'Premi E per usare' },
  'race.gotItem': { en: 'Got {item}!', it: 'Ottenuto: {item}!' },
  'race.hitBy': { en: 'Hit by {item}!', it: 'Colpito da {item}!' },
  'race.youHit': { en: '{victim} hit!', it: '{victim} colpito!' },
  'race.itemBlocked': { en: 'Shield absorbed the hit!', it: 'Lo scudo ha assorbito il colpo!' },
  'race.itemReady': { en: '{item} active', it: '{item} attivo' },
  'race.reflected': { en: 'Reflected {item} back!', it: '{item} riflesso al mittente!' },
  'race.rerolled': { en: 'The kiln gives you {item}!', it: 'La fornace ti d\u00e0 {item}!' },
  'race.hexed': { en: 'Caught in {item}!', it: 'Preso da {item}!' },
  // finish-line banner (short: it is set in display type at ~13vw)
  'race.finishKicker': { en: 'Finish', it: 'Arrivo' },
  'race.finishSubWin': { en: 'You take the win!', it: 'Vittoria!' },
  'race.finishSubPodium': { en: 'On the podium', it: 'Sul podio' },
  'race.finishSubDone': { en: 'Race complete', it: 'Gara completata' },
  'race.newBestTotal': { en: 'New best total time!', it: 'Nuovo miglior tempo totale!' },
  'race.newRecord': { en: 'NEW RECORD!', it: 'NUOVO RECORD!' },
  'race.ghostSaved': { en: 'Ghost saved', it: 'Ghost salvato' },
  'race.racingGhost': { en: 'Racing your ghost', it: 'Sfida il tuo ghost' },

  // ---------------- settings (new) ----------------
  'settings.items': { en: 'Power-ups', it: 'Potenziamenti' },
  'settings.music': { en: 'Music volume', it: 'Volume musica' },
  'settings.on': { en: 'On', it: 'On' },
  'settings.off': { en: 'Off', it: 'Off' },

  // ---------------- controls ----------------
  // (controls.help lives in the base dictionary - see i18n.js)

  // ---------------- tracks: names + what they teach + signature mechanic ----
  'track.sunforge': { en: 'Sunforge Circuit', it: 'Circuito Sunforge' },
  'track.sunforge.teach': { en: 'Drift charging and boost-pad rhythm', it: 'Carica in derapata e ritmo dei turbo' },
  'track.sunforge.mechanic': { en: 'Ancient gear monuments and a canyon shortcut', it: 'Monumenti a ingranaggi e scorciatoia nel canyon' },
  'track.ashfall': { en: 'Ashfall Run', it: 'Corsa delle Ceneri' },
  'track.ashfall.teach': { en: 'Reading chicanes without lifting', it: 'Leggere le chicane senza alzare il piede' },
  'track.ashfall.mechanic': { en: 'A sliding stone gate guards the dune straight', it: 'Un portale di pietra mobile difende il dritto delle dune' },
  'track.verdant': { en: 'Verdant Loop', it: 'Anello Verde' },
  'track.verdant.teach': { en: 'Smooth linked S-bends', it: 'Curve a S fluide e concatenate' },
  'track.verdant.mechanic': { en: 'Moss slicks and a swinging log', it: 'Muschio scivoloso e un tronco oscillante' },
  'track.neon': { en: 'Neon Cascade', it: 'Cascata Neon' },
  'track.neon.teach': { en: 'Hard 90° city corners at altitude', it: 'Angoli cittadini a 90° in quota' },
  'track.neon.mechanic': { en: 'Rooftop climbs with drop-offs on every side', it: 'Salite sui tetti con strapiombi ovunque' },
  'track.skyline': { en: 'Skyline Helix', it: 'Elica del Cielo' },
  'track.skyline.teach': { en: 'Managing elevation while holding speed', it: 'Gestire il dislivello mantenendo velocità' },
  'track.skyline.mechanic': { en: 'A spiraling climb around a mega-tower', it: 'Una salita a spirale attorno a una mega-torre' },
  'track.granite': { en: 'Granite Pass', it: 'Passo di Granito' },
  'track.granite.teach': { en: 'Brake planning into switchbacks', it: 'Pianificare la frenata nei tornanti' },
  'track.granite.mechanic': { en: 'A mountain climb with timed flame vents', it: 'Una scalata con getti di fiamma a tempo' },
  'track.magma': { en: 'Magma Coil', it: 'Spira di Magma' },
  'track.magma.teach': { en: 'Linking drifts around the caldera', it: 'Collegare derapate intorno al cratere' },
  'track.magma.mechanic': { en: 'Rhythmic flame jets inside the caldera', it: 'Getti di fiamma ritmici dentro il cratere' },
  'track.abyss': { en: 'Abyss Dock', it: 'Darsena dell\u2019Abisso' },
  'track.abyss.teach': { en: 'Using currents and buoyancy chambers', it: 'Sfruttare correnti e camere di galleggiamento' },
  'track.abyss.mechanic': { en: 'Water jets push you; low-g bubbles float you', it: 'I getti d\u2019acqua spingono, le bolle a bassa gravit\u00e0 ti fanno volare' },
  'track.forge': { en: 'Forge Line', it: 'Linea della Forgia' },
  'track.forge.teach': { en: 'Threading moving press arms', it: 'Infilarsi tra i bracci delle presse in moto' },
  'track.forge.mechanic': { en: 'Press alley + a boosted conveyor sector', it: 'Viale delle presse + settore conveyor con turbo' },
  'track.skyreach': { en: 'Skyreach', it: 'Vetta del Cielo' },
  'track.skyreach.teach': { en: 'Committing to long jumps between islands', it: 'Salti lunghi tra le isole senza esitare' },
  'track.skyreach.mechanic': { en: 'Updraft zones and island-hop ramps', it: 'Correnti ascensionali e rampe tra le isole' },
  'track.vael': { en: 'Ruins of Vael', it: 'Rovine di Vael' },
  'track.vael.teach': { en: 'Right-angle precision through colonnades', it: 'Precisione ad angolo retto tra i colonnati' },
  'track.vael.mechanic': { en: 'A rotating gear trap in the temple court', it: 'Una trappola a ingranaggi nel cortile del tempio' },
  'track.crown': { en: 'Sandstone Crown', it: 'Corona d\u2019Arenaria' },
  'track.crown.teach': { en: 'Defending a tight racing line', it: 'Difendere una traiettoria stretta' },
  'track.crown.mechanic': { en: 'Amphitheatre bowl with an infield thread', it: 'Anfiteatro con un tratto interno a filo' },
  'track.tempest': { en: 'Tempest Ridge', it: 'Cresta della Tempesta' },
  'track.tempest.teach': { en: 'Correcting for crosswind on exposed ridges', it: 'Correggere il vento trasversale sulle creste esposte' },
  'track.tempest.mechanic': { en: 'Crosswind zones that shove your kart sideways', it: 'Zone di vento che spingono il kart di lato' },
  'track.glimmer': { en: 'Glimmer Deep', it: 'Abisso Scintillante' },
  'track.glimmer.teach': { en: 'Using crystal springs as launch pads', it: 'Usare le sorgenti di cristallo come trampolini' },
  'track.glimmer.mechanic': { en: 'Glowing crystals and tall spring ramps', it: 'Cristalli luminosi e rampe a molla altissime' },
  'track.orbital': { en: 'Orbital Ring', it: 'Anello Orbitale' },
  'track.orbital.teach': { en: 'Carrying huge speed through low-g sweepers', it: 'Portare tanta velocit\u00e0 nei curvoni a bassa gravit\u00e0' },
  'track.orbital.mechanic': { en: 'A hull-breach sector with floaty physics', it: 'Un settore con breccia nello scafo e fisica fluttuante' },
  'track.void': { en: 'Void Terminal', it: 'Terminal del Vuoto' },

  // ---------------- cups & trophies ----------------
  'cup.ember': { en: 'Ember Cup', it: 'Coppa Brace' },
  'cup.ember.trophy': { en: 'The Dawn Trophy', it: 'Trofeo dell\u2019Alba' },
  'cup.ember.desc': { en: 'Gentle tracks to learn the drift.', it: 'Piste gentili per imparare la derapata.' },
  'cup.gear': { en: 'Gear Cup', it: 'Coppa Ingranaggio' },
  'cup.gear.trophy': { en: 'The Cogwheel Trophy', it: 'Trofeo dell\u2019Ingranaggio' },
  'cup.gear.desc': { en: 'Traps and hazards join the party.', it: 'Trappole e pericoli entrano in gioco.' },
  'cup.neon': { en: 'Neon Cup', it: 'Coppa Neon' },
  'cup.neon.trophy': { en: 'The Skyline Trophy', it: 'Trofeo dello Skyline' },
  'cup.neon.desc': { en: 'City lights and zero forgiveness.', it: 'Luci cittadine e zero indulgenza.' },
  'cup.storm': { en: 'Storm Cup', it: 'Coppa Tempesta' },
  'cup.storm.trophy': { en: 'The Thunderhead Trophy', it: 'Trofeo del Temporale' },
  'cup.storm.desc': { en: 'Wind, flame and altitude.', it: 'Vento, fiamme e altitudine.' },
  'cup.crown': { en: 'Crown Cup', it: 'Coppa Corona' },
  'cup.crown.trophy': { en: 'The Regal Trophy', it: 'Trofeo Regale' },
  'cup.crown.desc': { en: 'Four laps of the hardest classics.', it: 'Quattro giri sui classici pi\u00f9 duri.' },
  'cup.sunforge': { en: 'Sunforge Championship', it: 'Campionato Sunforge' },
  'cup.sunforge.trophy': { en: 'The Sunforge Crown', it: 'La Corona Sunforge' },
  'cup.sunforge.desc': { en: 'The ultimate test. No mercy.', it: 'La prova definitiva. Nessuna piet\u00e0.' },
  'trophy.platinum': { en: 'Platinum', it: 'Platino' },
  'trophy.gold': { en: 'Gold', it: 'Oro' },
  'trophy.silver': { en: 'Silver', it: 'Argento' },
  'trophy.bronze': { en: 'Bronze', it: 'Bronzo' },

  // ---------------- modes & flow ----------------
  'menu.quick': { en: 'Quick Race', it: 'Gara Rapida' },
  'menu.quickHint': { en: 'One race, any track, up to 8 karts', it: 'Una gara, qualsiasi pista, fino a 8 kart' },
  'menu.gpHint': { en: 'Four-track cup, points decide', it: 'Coppa di quattro piste, contano i punti' },
  'menu.ttHint': { en: 'Chase the clock, beat the ghost', it: 'Sfida il cronometro, batti il ghost' },
  'menu.battleHint': { en: 'Arena combat, last one floating', it: 'Combattimento nell\u2019arena' },
  'menu.onlineHint': { en: 'Race friends around the world', it: 'Sfida amici in tutto il mondo' },
  'menu.grandprix': { en: 'Grand Prix', it: 'Gran Premio' },
  'menu.timetrial': { en: 'Time Trial', it: 'Prova a Tempo' },
  'menu.battle': { en: 'Battle Mode', it: 'Modalit\u00e0 Battaglia' },
  'menu.garage': { en: 'Garage', it: 'Garage' },
  'menu.records': { en: 'Records', it: 'Record' },
  'menu.online': { en: 'Online', it: 'Online' },
  'menu.selectTrack': { en: 'Select Track', it: 'Scegli la pista' },
  'menu.selectCup': { en: 'Select Cup', it: 'Scegli la coppa' },
  'menu.back': { en: 'Back', it: 'Indietro' },
  'menu.continue': { en: 'Continue', it: 'Continua' },
  'menu.locked': { en: 'Locked', it: 'Bloccato' },
  'gp.raceOf': { en: 'Race {race}/{total}', it: 'Gara {race}/{total}' },
  'gp.standings': { en: 'Standings', it: 'Classifica' },
  'gp.points': { en: '{points} pts', it: '{points} pt' },
  'gp.trophyWon': { en: '{trophy} Trophy won!', it: 'Trofeo {trophy} conquistato!' },
  'gp.noTrophy': { en: 'No trophy this time - try again!', it: 'Nessun trofeo stavolta: riprova!' },
  'gp.playerChampion': { en: 'CHAMPION!', it: 'CAMPIONE!' },
  'tt.bestTotal': { en: 'Best total', it: 'Miglior totale' },
  'tt.bestLap': { en: 'Best lap', it: 'Miglior giro' },
  'tt.ghostBest': { en: 'Ghost: best run', it: 'Ghost: miglior giro' },
  'tt.noRecord': { en: 'No record yet', it: 'Ancora nessun record' },
  'tt.splits': { en: 'Splits', it: 'Intermedi' },
  'tt.raceGhost': { en: 'Race the ghost!', it: 'Sfida il ghost!' },
  'track.void.teach': { en: 'Everything at once: the final exam', it: 'Tutto insieme: l\u2019esame finale' },
  'track.void.mechanic': { en: 'Low-g docks, gear traps and vent flames', it: 'Darsene a bassa gravit\u00e0, ingranaggi e fiamme di sfiato' },

  // ---------------- battle arenas ----------------
  'menu.selectMode': { en: 'Battle Mode', it: 'Modalit\u00e0 battaglia' },
  'menu.selectArena': { en: 'Arena', it: 'Arena' },
  'battle.start': { en: 'Start Battle', it: 'Inizia battaglia' },
  'battle.energy': { en: 'Energy Rush', it: 'Raccolta di energia' },
  'battle.energy.d': { en: 'Collect energy cores from item boxes - first to 8 wins!', it: 'Raccogli nuclei energetici dalle casse: il primo a 8 vince!' },
  'battle.elimination': { en: 'Elimination', it: 'Eliminazione' },
  'battle.elimination.d': { en: 'Every hit costs HP - last kart standing wins', it: 'Ogni colpo costa HP: vince l\u2019ultimo kart in piedi' },
  'battle.zones': { en: 'Zone Control', it: 'Controllo zone' },
  'battle.zones.d': { en: 'Capture and hold the rings to bank points', it: 'Cattura e difendi gli anelli per accumulare punti' },
  'battle.survival': { en: 'Survival', it: 'Sopravvivenza' },
  'battle.survival.d': { en: 'HP drains over time and from hits - outlast everyone', it: 'Gli HP calano col tempo e con i colpi: resisti pi\u00f9 di tutti' },
  'battle.score': { en: 'Score Battle', it: 'Battaglia a punti' },
  'battle.score.d': { en: '+1 per hit, +2 per KO - most points when time is up wins', it: '+1 per colpo, +2 per KO: il punteggio pi\u00f9 alto vince' },
  'battle.ko': { en: '{name} knocked out!', it: '{name} eliminato!' },
  'battle.win': { en: '{name} wins the battle!', it: '{name} vince la battaglia!' },
  'battle.timeUp': { en: 'TIME UP!', it: 'TEMPO SCADUTO!' },
  'battle.cores': { en: '{cores}/{goal} cores', it: '{cores}/{goal} nuclei' },
  'battle.hp': { en: 'HP', it: 'HP' },
  'arena.emberForge': { en: 'Ember Forge', it: 'Forgia Ardente' },
  'arena.emberForge.desc': { en: 'Flame jets scorch the forge floor', it: 'Getti di fiamma bruciano il pavimento della forgia' },
  'arena.cryoHall': { en: 'Cryo Hall', it: 'Sala di Cristallo' },
  'arena.cryoHall.desc': { en: 'Sliding crystal shards patrol the hall', it: 'Schegge di cristallo scivolano nella sala' },
  'arena.neonPlaza': { en: 'Neon Plaza', it: 'Piazza Neon' },
  'arena.neonPlaza.desc': { en: 'Pendulums sweep the neon square', it: 'Pendoli spazzano la piazza al neon' },
  'arena.skyAtoll': { en: 'Sky Atoll', it: 'Atollo Celeste' },
  'arena.skyAtoll.desc': { en: 'Low gravity - float and strike', it: 'Bassa gravit\u00e0: galleggia e colpisci' },

  // ---------------- progression & achievements ----------------
  'race.boardRank': { en: 'Leaderboard: rank {rank}', it: 'Classifica: posizione {rank}' },
  'progression.xp': { en: '+{xp} XP', it: '+{xp} PE' },
  'progression.levelUp': { en: 'LEVEL {level}!', it: 'LIVELLO {level}!' },
  'progression.unlocked': { en: 'Unlocked: {item}', it: 'Sbloccato: {item}' },
  'achievement.earned': { en: 'Achievement: {name}', it: 'Traguardo: {name}' },

  'ach.firstRace': { en: 'Ignition', it: 'Accensione' },
  'ach.firstRace.d': { en: 'Finish your first race', it: 'Completa la tua prima gara' },
  'ach.firstWin': { en: 'First Flame', it: 'Prima fiamma' },
  'ach.firstWin.d': { en: 'Win a race', it: 'Vinci una gara' },
  'ach.podium10': { en: 'Podium Regular', it: 'Abitu\u00e9 del podio' },
  'ach.podium10.d': { en: 'Finish top 3 ten times', it: 'Arriva nei primi 3 dieci volte' },
  'ach.lap50': { en: 'Lap Collector', it: 'Collezionista di giri' },
  'ach.lap50.d': { en: 'Complete 50 laps', it: 'Completa 50 giri' },
  'ach.fastest5': { en: 'Hot Streak', it: 'Scia rovente' },
  'ach.fastest5.d': { en: 'Set 5 fastest laps', it: 'Firma 5 giri pi\u00f9 veloci' },
  'ach.record1': { en: 'Time Keeper', it: 'Custode del tempo' },
  'ach.record1.d': { en: 'Set a time trial record', it: 'Stabilisci un record a tempo' },
  'ach.record8': { en: 'Record Hunter', it: 'Cacciatore di record' },
  'ach.record8.d': { en: 'Set 8 time trial records', it: 'Stabilisci 8 record a tempo' },
  'ach.cup1': { en: 'Cup Collector', it: 'Collezionista di coppe' },
  'ach.cup1.d': { en: 'Win any cup trophy', it: 'Vinci un trofeo di coppa' },
  'ach.cupGold': { en: 'Golden Hands', it: 'Mani d\u2019oro' },
  'ach.cupGold.d': { en: 'Win a Gold trophy', it: 'Vinci un trofeo d\u2019oro' },
  'ach.cupPlatinum': { en: 'Forge Master', it: 'Maestro della forgia' },
  'ach.cupPlatinum.d': { en: 'Win a Platinum trophy', it: 'Vinci un trofeo di platino' },
  'ach.items20': { en: 'Arsenal', it: 'Arsenale' },
  'ach.items20.d': { en: 'Use 20 power-ups', it: 'Usa 20 potenziamenti' },
  'ach.items30': { en: 'Lucky Crate', it: 'Cassa fortunata' },
  'ach.items30.d': { en: 'Collect 30 power-ups', it: 'Raccogli 30 potenziamenti' },
  'ach.ghost1': { en: 'Ghost Rider', it: 'Cavaliere fantasma' },
  'ach.ghost1.d': { en: 'Race against a ghost', it: 'Gareggia contro un ghost' },
  'ach.explorer': { en: 'Explorer', it: 'Esploratore' },
  'ach.explorer.d': { en: 'Race on all 16 tracks', it: 'Corri su tutte le 16 piste' },
  'ach.level5': { en: 'Rising Star', it: 'Stella nascente' },
  'ach.level5.d': { en: 'Reach level 5', it: 'Raggiungi il livello 5' },
  'ach.level10': { en: 'Sunforged', it: 'Forgiato dal sole' },
  'ach.level10.d': { en: 'Reach level 10', it: 'Raggiungi il livello 10' },
};
