// ============================================================================
// Localized names/descriptions for content (characters, parts, items...).
// Merged into the main dictionary by i18n.js - content keeps its strings
// next to its data. Every key has EN + IT (verified by tests).
// ============================================================================

export const CONTENT_STRINGS = {
  // ---------------- characters ----------------
  'char.ember': { en: 'Ember', it: 'Ember' },
  'char.ember.species': { en: 'the Dustfox', it: 'la Volpe delle Sabbie' },
  'char.ember.personality': { en: 'Balanced daredevil with fire in her tail', it: 'Temeraria equilibrata con il fuoco nella coda' },
  'char.cinder': { en: 'Cinder', it: 'Cinder' },
  'char.cinder.species': { en: 'the Magmabear', it: 'l\u2019Orso di Magma' },
  'char.cinder.personality': { en: 'Heavyweight bruiser, first into every brawl', it: 'Peso massimo aggressivo, sempre primo nella mischia' },
  'char.zephyr': { en: 'Zephyr', it: 'Zephyr' },
  'char.zephyr.species': { en: 'the Windheron', it: 'l\u2019Airone del Vento' },
  'char.zephyr.personality': { en: 'Feather-light and quick off the line', it: 'Leggero come una piuma, scatto bruciante' },
  'char.bastion': { en: 'Bastion', it: 'Bastion' },
  'char.bastion.species': { en: 'the Ironshell', it: 'il Guscio di Ferro' },
  'char.bastion.personality': { en: 'Unmovable wall, shrugs off every hit', it: 'Muro inamovibile, ignora ogni colpo' },
  'char.nova': { en: 'Nova', it: 'Nova' },
  'char.nova.species': { en: 'the Starlynx', it: 'la Lince Stellare' },
  'char.nova.personality': { en: 'Chases pure top speed, fragile but fast', it: 'Insegue la velocit\u00e0 pura, fragile ma velocissima' },
  'char.thistle': { en: 'Thistle', it: 'Thistle' },
  'char.thistle.species': { en: 'the Bramblehop', it: 'il Salto di Rovo' },
  'char.thistle.personality': { en: 'Twitchy corner dancer, impossible to box out', it: 'Danzatore di curve, impossibile da chiudere' },
  'char.coral': { en: 'Coral', it: 'Coral' },
  'char.coral.species': { en: 'the Tidedrake', it: 'il Drago delle Maree' },
  'char.coral.personality': { en: 'At home on any surface, wet or wild', it: 'A suo agio su ogni superficie, bagnata o selvaggia' },
  'char.volt': { en: 'Volt', it: 'Volt' },
  'char.volt.species': { en: 'the Stormkit', it: 'il Cucciolo della Tempesta' },
  'char.volt.personality': { en: 'Explodes off the start, never stops buzzing', it: 'Esplode alla partenza, non smette mai di vibrare' },
  'char.obsidian': { en: 'Obsidian', it: 'Obsidian' },
  'char.obsidian.species': { en: 'the Ashwing', it: 'l\u2019Ala di Cenere' },
  'char.obsidian.personality': { en: 'Drift artist from the dark side of the caldera', it: 'Artista della derapata dal lato buio del cratere' },
  'char.juniper': { en: 'Juniper', it: 'Juniper' },
  'char.juniper.species': { en: 'the Mosscat', it: 'il Gatto di Muschio' },
  'char.juniper.personality': { en: 'Forest wanderer, treats dirt like tarmac', it: 'Nomade della foresta, tratta lo sterrato come asfalto' },
  'char.ratchet': { en: 'Ratchet', it: 'Ratchet' },
  'char.ratchet.species': { en: 'the Scraprat', it: 'il Ratto di Rottami' },
  'char.ratchet.personality': { en: 'Grease-stained tinkerer with a heavy wrench', it: 'Meccanico unto con una chiave pesante' },
  'char.lumi': { en: 'Lumi', it: 'Lumi' },
  'char.lumi.species': { en: 'the Frostowl', it: 'il Gufo di Gelo' },
  'char.lumi.personality': { en: 'Calm, precise, slices corners like ice', it: 'Calmo, preciso, taglia le curve come ghiaccio' },
  'char.aurelia': { en: 'Aurelia', it: 'Aurelia' },
  'char.aurelia.species': { en: 'the Sundancer', it: 'la Danzatrice del Sole' },
  'char.aurelia.personality': { en: 'Golden champion of the Crown Circuit', it: 'Campionessa dorata del Circuito della Corona' },
  'char.umbra': { en: 'Umbra', it: 'Umbra' },
  'char.umbra.species': { en: 'the Voidmole', it: 'la Talpa del Vuoto' },
  'char.umbra.personality': { en: 'Digs through shortcuts nobody else can see', it: 'Scava scorciatoie che nessun altro riesce a vedere' },
  'unlock.aurelia': { en: 'Win the Crown Cup', it: 'Vinci la Coppa Corona' },
  'unlock.umbra': { en: 'Complete the Night Shift achievement', it: 'Completa l\u2019impresa Turno di Notte' },

  // ---------------- chassis ----------------
  'chassis.duneBlazer': { en: 'Dune Blazer MK-1', it: 'Dune Blazer MK-1' },
  'chassis.duneBlazer.desc': { en: 'The trusty all-rounder from the Sunforge garage.', it: 'L\u2019affidabile tuttofare dell\u2019officina Sunforge.' },
  'chassis.featherwing': { en: 'Featherwing', it: 'Ala di Piuma' },
  'chassis.featherwing.desc': { en: 'So light it leaps. Gives up top speed for zip.', it: 'Cos\u00ec leggero che vola. Rinuncia alla velocit\u00e0 per lo scatto.' },
  'chassis.ironcladHauler': { en: 'Ironclad Hauler', it: 'Corazzato da Traino' },
  'chassis.ironcladHauler.desc': { en: 'A rolling fortress. Slow to wake, hard to stop.', it: 'Una fortezza su ruote. Lento a svegliarsi, difficile da fermare.' },
  'chassis.tempestBolt': { en: 'Tempest Bolt', it: 'Fulmine Tempesta' },
  'chassis.tempestBolt.desc': { en: 'Built for screaming straights. Nervous in corners.', it: 'Fatto per rettilinei urlanti. Nervoso in curva.' },
  'chassis.bumblewisp': { en: 'Bumblewisp', it: 'Soffio di Calabrone' },
  'chassis.bumblewisp.desc': { en: 'A corner-hugging honeybee. Slower on the open road.', it: 'Un\u2019ape che abbraccia le curve. Pi\u00f9 lento sul dritto.' },
  'chassis.rockjaw': { en: 'Rockjaw', it: 'Mascella di Roccia' },
  'chassis.rockjaw.desc': { en: 'Eats rough terrain for breakfast. Heavy and blunt.', it: 'Divora terreni accidentati a colazione. Pesante e diretto.' },
  'chassis.cometCourier': { en: 'Comet Courier', it: 'Corriere Cometa' },
  'chassis.cometCourier.desc': { en: 'Launches like a comet, slides wide if you blink.', it: 'Parte come una cometa, allarga la traiettoria se sbatti le palpebre.' },
  'chassis.gearworkRoyale': { en: 'Gearwork Royale', it: 'Ingranaggio Reale' },
  'chassis.gearworkRoyale.desc': { en: 'Ancient gear-tech tuned for silky drifts.', it: 'Antica tecnologia a ingranaggi per derapate setose.' },

  // ---------------- wheels ----------------
  'wheel.standard': { en: 'Standard Treads', it: 'Cingoli Standard' },
  'wheel.slimline': { en: 'Slimline Racers', it: 'Cerchi Filanti' },
  'wheel.duneRollers': { en: 'Dune Rollers', it: 'Rulli delle Dune' },
  'wheel.gyroRings': { en: 'Gyro Rings', it: 'Anelli Giroscopici' },
  'wheel.ironDrums': { en: 'Iron Drums', it: 'Tamburi di Ferro' },
  'wheel.slickComets': { en: 'Slick Comets', it: 'Comete Slick' },
  'wheel.stormSpikes': { en: 'Storm Spikes', it: 'Punte della Tempesta' },
  'wheel.chromeHalos': { en: 'Chrome Halos', it: 'Aure Cromate' },
  'wheel.mossGrippers': { en: 'Moss Grippers', it: 'Aderenti di Muschio' },
  'wheel.turboSprockets': { en: 'Turbo Sprockets', it: 'Ruote Dentate Turbo' },
  'wheel.balloonFloaters': { en: 'Balloon Floaters', it: 'Palloni Galleggianti' },
  'wheel.rallyHex': { en: 'Rally Hex', it: 'Esagonali da Rally' },

  // ---------------- cosmetics ----------------
  'paint.sunsetOrange': { en: 'Sunset Orange', it: 'Arancio Tramonto' },
  'paint.duneTeal': { en: 'Dune Teal', it: 'Verde Acqua Duna' },
  'paint.emberRed': { en: 'Ember Red', it: 'Rosso Brace' },
  'paint.canyonCream': { en: 'Canyon Cream', it: 'Crema del Canyon' },
  'paint.nightInk': { en: 'Night Ink', it: 'Inchiostro Notturno' },
  'paint.forestMoss': { en: 'Forest Moss', it: 'Muschio di Foresta' },
  'paint.royalViolet': { en: 'Royal Violet', it: 'Viola Reale' },
  'paint.stormYellow': { en: 'Storm Yellow', it: 'Giallo Tempesta' },
  'paint.glacierBlue': { en: 'Glacier Blue', it: 'Blu Ghiacciaio' },
  'paint.magmaBlack': { en: 'Magma Black', it: 'Nero Magma' },
  'paint.coralPink': { en: 'Coral Pink', it: 'Rosa Corallo' },
  'paint.bronzeGear': { en: 'Bronze Gear', it: 'Bronzo Ingranaggio' },
  'paint.silverMist': { en: 'Silver Mist', it: 'Nebbia d\u2019Argento' },
  'paint.goldForge': { en: 'Gold Forge', it: 'Oro della Forgia' },
  'paint.prismPearl': { en: 'Prism Pearl', it: 'Perla Prisma' },
  'paint.voidChrome': { en: 'Void Chrome', it: 'Cromo del Vuoto' },

  'decal.none': { en: 'Clean', it: 'Pulito' },
  'decal.racingStripe': { en: 'Racing Stripe', it: 'Striscia da Corsa' },
  'decal.sunEmblem': { en: 'Sun Emblem', it: 'Emblema Solare' },
  'decal.gearStamp': { en: 'Gear Stamp', it: 'Stampo a Ingranaggio' },
  'decal.flameTrail': { en: 'Flame Trail', it: 'Scia di Fiamme' },
  'decal.stormBolt': { en: 'Storm Bolt', it: 'Fulmine Tempesta' },
  'decal.waveCrest': { en: 'Wave Crest', it: 'Cresta d\u2019Onda' },
  'decal.starField': { en: 'Star Field', it: 'Campo Stellato' },

  'exhaust.twinPipes': { en: 'Twin Pipes', it: 'Doppio Scarico' },
  'exhaust.stackVents': { en: 'Stack Vents', it: 'Sfiati Verticali' },
  'exhaust.quadBurst': { en: 'Quad Burst', it: 'Quadruplo Scoppio' },
  'exhaust.turbineRing': { en: 'Turbine Ring', it: 'Anello Turbina' },

  'effect.classicFlame': { en: 'Classic Flame', it: 'Fiamma Classica' },
  'effect.emberTrail': { en: 'Ember Trail', it: 'Scia di Braci' },
  'effect.frostWake': { en: 'Frost Wake', it: 'Scia Gelata' },
  'effect.venomSpark': { en: 'Venom Spark', it: 'Scintilla Velenosa' },
  'effect.voidShimmer': { en: 'Void Shimmer', it: 'Bagliore del Vuoto' },

  // ---------------- items (22 originals) ----------------
  'item.fluxBolt': { en: 'Flux Bolt', it: 'Dardo di Flusso' },
  'item.fluxBolt.desc': { en: 'Homing bolt that locks onto engine heat ahead of you.', it: 'Dardo a ricerca che aggancia il calore del motore davanti a te.' },
  'item.fluxBolt.counter': { en: 'Drift hard to break the lock.', it: 'Derapata decisa per rompere l\u2019aggancio.' },
  'item.gravityAnchor': { en: 'Gravity Anchor', it: 'Ancora Gravitazionale' },
  'item.gravityAnchor.desc': { en: 'Pins the kart ahead to the road: no hops, no drifts, less speed.', it: 'Inchioda il kart davanti all\u2019asfalto: niente salti, niente derapate, meno velocit\u00e0.' },
  'item.gravityAnchor.counter': { en: 'Cleanse with a Pulse Ring or block with a shield.', it: 'Rimuovi con Anello Pulsante o blocca con uno scudo.' },
  'item.mirageClone': { en: 'Mirage Clone', it: 'Clone Miraggio' },
  'item.mirageClone.desc': { en: 'Drops a hologram behind you that eats one hit and flashes.', it: 'Lascia un ologramma dietro di te che assorbe un colpo e abbaglia.' },
  'item.mirageClone.counter': { en: 'Clones shimmer - shoot the real kart instead.', it: 'I cloni tremolano: colpisci il kart vero.' },
  'item.pulseRing': { en: 'Pulse Ring', it: 'Anello Pulsante' },
  'item.pulseRing.desc': { en: 'A wave that erases nearby hazards and cleanses your debuffs.', it: 'Un\u2019onda che cancella i pericoli vicini e rimuove i tuoi malus.' },
  'item.pulseRing.counter': { en: 'Short radius - timing matters.', it: 'Raggio corto: il tempismo conta.' },
  'item.overdriveCore': { en: 'Overdrive Core', it: 'Nucleo Fuorigiri' },
  'item.overdriveCore.desc': { en: 'Violent burst of speed, but your steering goes twitchy and drifts die.', it: 'Esplosione di velocit\u00e0, ma lo sterzo diventa nervoso e le derapate spariscono.' },
  'item.overdriveCore.counter': { en: 'Its own drawback is the counterplay.', it: 'Il suo difetto \u00e8 la contromossa.' },
  'item.vortexMine': { en: 'Vortex Mine', it: 'Mina Vortice' },
  'item.vortexMine.desc': { en: 'Dropped mine that drags karts in, then launches them skyward.', it: 'Mina che trascina i kart verso di s\u00e9 e li lancia in aria.' },
  'item.vortexMine.counter': { en: 'Visible and avoidable - take the wide line.', it: 'Visibile ed evitabile: allarga la traiettoria.' },
  'item.phaseShield': { en: 'Phase Shield', it: 'Scudo di Fase' },
  'item.phaseShield.desc': { en: 'Slip through karts and hazards for 4s - but you can\u2019t grab items.', it: 'Attraversa kart e pericoli per 4s, ma niente oggetti.' },
  'item.phaseShield.counter': { en: 'You can\u2019t attack or collect while phased.', it: 'In fase non puoi attaccare n\u00e9 raccogliere.' },
  'item.timeRipple': { en: 'Time Ripple', it: 'Increspatura Temporale' },
  'item.timeRipple.desc': { en: 'A bubble that slows every rival inside it. You are exempt.', it: 'Una bolla che rallenta ogni rivale al suo interno. Tu sei escluso.' },
  'item.timeRipple.counter': { en: 'Audible windup - sprint out of the radius.', it: 'Carica udibile: esci dal raggio.' },
  'item.magnetSurge': { en: 'Magnet Surge', it: 'Scarica Magnetica' },
  'item.magnetSurge.desc': { en: 'Item boxes fly toward you for a few seconds.', it: 'Le casse oggetto volano verso di te per qualche secondo.' },
  'item.magnetSurge.counter': { en: 'Only helps near boxes.', it: 'Utile solo vicino alle casse.' },
  'item.repairDrone': { en: 'Repair Drone', it: 'Drone Riparatore' },
  'item.repairDrone.desc': { en: 'Cleanses debuffs, patches on a shield charge and a little boost.', it: 'Rimuove i malus, aggiunge una carica scudo e un po\u2019 di boost.' },
  'item.repairDrone.counter': { en: 'Reactive, not proactive.', it: 'Reattivo, non proattivo.' },
  'item.echoSnare': { en: 'Echo Snare', it: 'Laccio Eco' },
  'item.echoSnare.desc': { en: 'Wraps the target\u2019s steering in echoes - it reverses briefly.', it: 'Avvolge lo sterzo del bersaglio in echi: si inverte per un istante.' },
  'item.echoSnare.counter': { en: 'Release a drift to snap out of it faster.', it: 'Rilascia una derapata per liberarti prima.' },
  'item.prismWall': { en: 'Prism Wall', it: 'Muro Prisma' },
  'item.prismWall.desc': { en: 'A glass wall behind you: anyone crossing it is badly slowed.', it: 'Un muro di vetro dietro di te: chi lo attraversa rallenta di colpo.' },
  'item.prismWall.counter': { en: 'Narrow - go around it.', it: 'Stretto: aggiralo.' },
  'item.slipstreamHarpoon': { en: 'Slipstream Harpoon', it: 'Arpione di Scia' },
  'item.slipstreamHarpoon.desc': { en: 'Hook the kart ahead and get yanked toward it.', it: 'Aggancia il kart davanti e fatti trascinare verso di lui.' },
  'item.slipstreamHarpoon.counter': { en: 'The target breaks free by boosting.', it: 'Il bersaglio si libera con un boost.' },
  'item.staticBloom': { en: 'Static Bloom', it: 'Fiore Statico' },
  'item.staticBloom.desc': { en: 'Thrown seed that blooms into a field killing drift charge.', it: 'Seme lanciato che fiorisce in un campo che azzera la carica derapata.' },
  'item.staticBloom.counter': { en: 'Clearly visible - steer around the petals.', it: 'Ben visibile: sterza attorno ai petali.' },
  'item.chronoShard': { en: 'Chrono Shard', it: 'Scheggia Crono' },
  'item.chronoShard.desc': { en: 'Snapshots your speed; if you get slowed hard, it snaps you back.', it: 'Fotografa la tua velocit\u00e0; se rallenti di colpo, ti ci riporta.' },
  'item.chronoShard.counter': { en: 'Single use, timing is everything.', it: 'Uso singolo: il tempismo \u00e8 tutto.' },
  'item.ionLash': { en: 'Ion Lash', it: 'Frusta Ionica' },
  'item.ionLash.desc': { en: 'Front arc whip: knocks rivals sideways and steals their charge.', it: 'Frusta ad arco frontale: sposta i rivali e ruba la loro carica.' },
  'item.ionLash.counter': { en: 'Very short range.', it: 'Portata brevissima.' },
  'item.decoyBeacon': { en: 'Decoy Beacon', it: 'Faro Esca' },
  'item.decoyBeacon.desc': { en: 'Thrown beacon that retargets enemy projectiles to itself.', it: 'Faro lanciato che devia su di s\u00e9 i proiettili nemici.' },
  'item.decoyBeacon.counter': { en: 'Only fools projectiles.', it: 'Inganna solo i proiettili.' },
  'item.gravitonWell': { en: 'Graviton Well', it: 'Pozzo Gravitonico' },
  'item.gravitonWell.desc': { en: 'A pocket of heavy gravity that bends rivals off their line.', it: 'Una sacca di gravit\u00e0 pesante che piega i rivali fuori linea.' },
  'item.gravitonWell.counter': { en: 'Wide and visible - give it room.', it: 'Ampio e visibile: dagli spazio.' },
  'item.tempestCell': { en: 'Tempest Cell', it: 'Cella Tempesta' },
  'item.tempestCell.desc': { en: 'Your next 3 drift boosts zap rivals right behind you.', it: 'I prossimi 3 boost di derapata fulminano chi ti segue.' },
  'item.tempestCell.counter': { en: 'Requires drifting; zaps only behind.', it: 'Richiede derapate; colpisce solo dietro.' },
  'item.nanoSwarm': { en: 'Nano Swarm', it: 'Sciame Nano' },
  'item.nanoSwarm.desc': { en: 'A cone of gnats behind you that drags anyone who flies into it.', it: 'Un cono di zanzare dietro di te che frena chi ci vola dentro.' },
  'item.nanoSwarm.counter': { en: 'Pass on the other side.', it: 'Supera dall\u2019altro lato.' },
  'item.auroraVeil': { en: 'Aurora Veil', it: 'Velo d\u2019Aurora' },
  'item.auroraVeil.desc': { en: 'A shimmering ribbon that makes it icy-slippery to cross.', it: 'Un nastro cangiante che diventa ghiaccio scivoloso al passaggio.' },
  'item.auroraVeil.counter': { en: 'Avoid the ribbon.', it: 'Evita il nastro.' },
  'item.kineticSiphon': { en: 'Kinetic Siphon', it: 'Sifone Cinetico' },
  'item.kineticSiphon.desc': { en: 'Drains a little speed from the kart ahead and feeds it to you.', it: 'Aspira un po\u2019 di velocit\u00e0 dal kart davanti e la d\u00e0 a te.' },
  'item.kineticSiphon.counter': { en: 'Break line of sight or boost away.', it: 'Rompi la linea di vista o scappa col boost.' },

  // ---------------- HUD / race (new) ----------------
  'hud.item': { en: 'ITEM', it: 'OGGETTO' },
  'hud.itemHint': { en: 'Press E to use', it: 'Premi E per usare' },
  'race.gotItem': { en: 'Got {item}!', it: 'Ottenuto: {item}!' },
  'race.hitBy': { en: 'Hit by {item}!', it: 'Colpito da {item}!' },
  'race.youHit': { en: '{victim} hit!', it: '{victim} colpito!' },
  'race.itemBlocked': { en: 'Shield absorbed the hit!', it: 'Lo scudo ha assorbito il colpo!' },
  'race.chronoRestore': { en: 'Chrono restore!', it: 'Ripristino Crono!' },
  'race.newBestTotal': { en: 'New best total time!', it: 'Nuovo miglior tempo totale!' },
  'race.newRecord': { en: 'NEW RECORD!', it: 'NUOVO RECORD!' },
  'race.ghostSaved': { en: 'Ghost saved', it: 'Ghost salvato' },
  'race.racingGhost': { en: 'Racing your ghost', it: 'Sfida il tuo ghost' },

  // ---------------- settings (new) ----------------
  'settings.items': { en: 'Power-ups', it: 'Potenziamenti' },
  'settings.music': { en: 'Music volume', it: 'Volume musica' },
  'settings.on': { en: 'On', it: 'On' },
  'settings.off': { en: 'Off', it: 'Off' },

  // ---------------- controls ----------------
  'controls.help': { en: 'WASD / Arrows drive · SHIFT drift · SPACE trick · E item · R reset · ESC pause',
                     it: 'WASD / Frecce guida · SHIFT derapata · SPACE acrobazia · E oggetto · R reset · ESC pausa' },

  // ---------------- tracks: names + what they teach + signature mechanic ----
  'track.sunforge': { en: 'Sunforge Circuit', it: 'Circuito Sunforge' },
  'track.sunforge.teach': { en: 'Drift charging and boost-pad rhythm', it: 'Carica in derapata e ritmo dei turbo' },
  'track.sunforge.mechanic': { en: 'Ancient gear monuments and a canyon shortcut', it: 'Monumenti a ingranaggi e scorciatoia nel canyon' },
  'track.ashfall': { en: 'Ashfall Run', it: 'Corsa delle Ceneri' },
  'track.ashfall.teach': { en: 'Reading chicanes without lifting', it: 'Leggere le chicane senza alzare il piede' },
  'track.ashfall.mechanic': { en: 'A sliding stone gate guards the dune straight', it: 'Un portale di pietra mobile difende il dritto delle dune' },
  'track.verdant': { en: 'Verdant Loop', it: 'Anello Verde' },
  'track.verdant.teach': { en: 'Smooth linked S-bends', it: 'Curve a S fluide e concatenate' },
  'track.verdant.mechanic': { en: 'Moss slicks and a swinging log', it: 'Muschio scivoloso e un tronco oscillante' },
  'track.neon': { en: 'Neon Cascade', it: 'Cascata Neon' },
  'track.neon.teach': { en: 'Hard 90° city corners at altitude', it: 'Angoli cittadini a 90° in quota' },
  'track.neon.mechanic': { en: 'Rooftop climbs with drop-offs on every side', it: 'Salite sui tetti con strapiombi ovunque' },
  'track.skyline': { en: 'Skyline Helix', it: 'Elica del Cielo' },
  'track.skyline.teach': { en: 'Managing elevation while holding speed', it: 'Gestire il dislivello mantenendo velocità' },
  'track.skyline.mechanic': { en: 'A spiraling climb around a mega-tower', it: 'Una salita a spirale attorno a una mega-torre' },
  'track.granite': { en: 'Granite Pass', it: 'Passo di Granito' },
  'track.granite.teach': { en: 'Brake planning into switchbacks', it: 'Pianificare la frenata nei tornanti' },
  'track.granite.mechanic': { en: 'A mountain climb with timed flame vents', it: 'Una scalata con getti di fiamma a tempo' },
  'track.magma': { en: 'Magma Coil', it: 'Spira di Magma' },
  'track.magma.teach': { en: 'Precision on a narrow, hostile line', it: 'Precisione su una linea stretta e ostile' },
  'track.magma.mechanic': { en: 'Rhythmic flame jets inside the caldera', it: 'Getti di fiamma ritmici dentro il cratere' },
  'track.abyss': { en: 'Abyss Dock', it: 'Darsena dell\u2019Abisso' },
  'track.abyss.teach': { en: 'Using currents and buoyancy chambers', it: 'Sfruttare correnti e camere di galleggiamento' },
  'track.abyss.mechanic': { en: 'Water jets push you; low-g bubbles float you', it: 'I getti d\u2019acqua spingono, le bolle a bassa gravit\u00e0 ti fanno volare' },
  'track.forge': { en: 'Forge Line', it: 'Linea della Forgia' },
  'track.forge.teach': { en: 'Threading moving press arms', it: 'Infilarsi tra i bracci delle presse in moto' },
  'track.forge.mechanic': { en: 'Press alley + a boosted conveyor sector', it: 'Viale delle presse + settore conveyor con turbo' },
  'track.skyreach': { en: 'Skyreach', it: 'Vetta del Cielo' },
  'track.skyreach.teach': { en: 'Committing to long jumps between islands', it: 'Salti lunghi tra le isole senza esitare' },
  'track.skyreach.mechanic': { en: 'Updraft zones and island-hop ramps', it: 'Correnti ascensionali e rampe tra le isole' },
  'track.vael': { en: 'Ruins of Vael', it: 'Rovine di Vael' },
  'track.vael.teach': { en: 'Right-angle precision through colonnades', it: 'Precisione ad angolo retto tra i colonnati' },
  'track.vael.mechanic': { en: 'A rotating gear trap in the temple court', it: 'Una trappola a ingranaggi nel cortile del tempio' },
  'track.crown': { en: 'Sandstone Crown', it: 'Corona d\u2019Arenaria' },
  'track.crown.teach': { en: 'Defending a tight racing line', it: 'Difendere una traiettoria stretta' },
  'track.crown.mechanic': { en: 'Amphitheatre bowl with an infield thread', it: 'Anfiteatro con un tratto interno a filo' },
  'track.tempest': { en: 'Tempest Ridge', it: 'Cresta della Tempesta' },
  'track.tempest.teach': { en: 'Correcting for crosswind on exposed ridges', it: 'Correggere il vento trasversale sulle creste esposte' },
  'track.tempest.mechanic': { en: 'Crosswind zones that shove your kart sideways', it: 'Zone di vento che spingono il kart di lato' },
  'track.glimmer': { en: 'Glimmer Deep', it: 'Abisso Scintillante' },
  'track.glimmer.teach': { en: 'Using crystal springs as launch pads', it: 'Usare le sorgenti di cristallo come trampolini' },
  'track.glimmer.mechanic': { en: 'Glowing crystals and tall spring ramps', it: 'Cristalli luminosi e rampe a molla altissime' },
  'track.orbital': { en: 'Orbital Ring', it: 'Anello Orbitale' },
  'track.orbital.teach': { en: 'Carrying huge speed through low-g sweepers', it: 'Portare tanta velocit\u00e0 nei curvoni a bassa gravit\u00e0' },
  'track.orbital.mechanic': { en: 'A hull-breach sector with floaty physics', it: 'Un settore con breccia nello scafo e fisica fluttuante' },
  'track.void': { en: 'Void Terminal', it: 'Terminal del Vuoto' },

  // ---------------- cups & trophies ----------------
  'cup.ember': { en: 'Ember Cup', it: 'Coppa Brace' },
  'cup.ember.trophy': { en: 'The Dawn Trophy', it: 'Trofeo dell\u2019Alba' },
  'cup.ember.desc': { en: 'Gentle tracks to learn the drift.', it: 'Piste gentili per imparare la derapata.' },
  'cup.gear': { en: 'Gear Cup', it: 'Coppa Ingranaggio' },
  'cup.gear.trophy': { en: 'The Cogwheel Trophy', it: 'Trofeo dell\u2019Ingranaggio' },
  'cup.gear.desc': { en: 'Traps and hazards join the party.', it: 'Trappole e pericoli entrano in gioco.' },
  'cup.neon': { en: 'Neon Cup', it: 'Coppa Neon' },
  'cup.neon.trophy': { en: 'The Skyline Trophy', it: 'Trofeo dello Skyline' },
  'cup.neon.desc': { en: 'City lights and zero forgiveness.', it: 'Luci cittadine e zero indulgenza.' },
  'cup.storm': { en: 'Storm Cup', it: 'Coppa Tempesta' },
  'cup.storm.trophy': { en: 'The Thunderhead Trophy', it: 'Trofeo del Temporale' },
  'cup.storm.desc': { en: 'Wind, flame and altitude.', it: 'Vento, fiamme e altitudine.' },
  'cup.crown': { en: 'Crown Cup', it: 'Coppa Corona' },
  'cup.crown.trophy': { en: 'The Regal Trophy', it: 'Trofeo Regale' },
  'cup.crown.desc': { en: 'Four laps of the hardest classics.', it: 'Quattro giri sui classici pi\u00f9 duri.' },
  'cup.sunforge': { en: 'Sunforge Championship', it: 'Campionato Sunforge' },
  'cup.sunforge.trophy': { en: 'The Sunforge Crown', it: 'La Corona Sunforge' },
  'cup.sunforge.desc': { en: 'The ultimate test. No mercy.', it: 'La prova definitiva. Nessuna piet\u00e0.' },
  'trophy.platinum': { en: 'Platinum', it: 'Platino' },
  'trophy.gold': { en: 'Gold', it: 'Oro' },
  'trophy.silver': { en: 'Silver', it: 'Argento' },
  'trophy.bronze': { en: 'Bronze', it: 'Bronzo' },

  // ---------------- modes & flow ----------------
  'menu.quick': { en: 'Quick Race', it: 'Gara Rapida' },
  'menu.grandprix': { en: 'Grand Prix', it: 'Gran Premio' },
  'menu.timetrial': { en: 'Time Trial', it: 'Prova a Tempo' },
  'menu.battle': { en: 'Battle Mode', it: 'Modalit\u00e0 Battaglia' },
  'menu.garage': { en: 'Garage', it: 'Garage' },
  'menu.records': { en: 'Records', it: 'Record' },
  'menu.online': { en: 'Online', it: 'Online' },
  'menu.selectTrack': { en: 'Select Track', it: 'Scegli la pista' },
  'menu.selectCup': { en: 'Select Cup', it: 'Scegli la coppa' },
  'menu.back': { en: 'Back', it: 'Indietro' },
  'menu.continue': { en: 'Continue', it: 'Continua' },
  'menu.locked': { en: 'Locked', it: 'Bloccato' },
  'gp.raceOf': { en: 'Race {race}/{total}', it: 'Gara {race}/{total}' },
  'gp.standings': { en: 'Standings', it: 'Classifica' },
  'gp.points': { en: '{points} pts', it: '{points} pt' },
  'gp.trophyWon': { en: '{trophy} Trophy won!', it: 'Trofeo {trophy} conquistato!' },
  'gp.noTrophy': { en: 'No trophy this time - try again!', it: 'Nessun trofeo stavolta: riprova!' },
  'gp.playerChampion': { en: 'CHAMPION!', it: 'CAMPIONE!' },
  'tt.bestTotal': { en: 'Best total', it: 'Miglior totale' },
  'tt.bestLap': { en: 'Best lap', it: 'Miglior giro' },
  'tt.ghostBest': { en: 'Ghost: best run', it: 'Ghost: miglior giro' },
  'tt.noRecord': { en: 'No record yet', it: 'Ancora nessun record' },
  'tt.splits': { en: 'Splits', it: 'Intermedi' },
  'tt.raceGhost': { en: 'Race the ghost!', it: 'Sfida il ghost!' },
  'track.void.teach': { en: 'Everything at once: the final exam', it: 'Tutto insieme: l\u2019esame finale' },
  'track.void.mechanic': { en: 'Low-g docks, gear traps and vent flames', it: 'Darsene a bassa gravit\u00e0, ingranaggi e fiamme di sfiato' },

  // ---------------- battle arenas ----------------
  'menu.selectMode': { en: 'Battle Mode', it: 'Modalit\u00e0 battaglia' },
  'menu.selectArena': { en: 'Arena', it: 'Arena' },
  'battle.start': { en: 'Start Battle', it: 'Inizia battaglia' },
  'battle.energy': { en: 'Energy Rush', it: 'Raccolta di energia' },
  'battle.energy.d': { en: 'Collect energy cores from item boxes - first to 8 wins!', it: 'Raccogli nuclei energetici dalle casse: il primo a 8 vince!' },
  'battle.elimination': { en: 'Elimination', it: 'Eliminazione' },
  'battle.elimination.d': { en: 'Every hit costs HP - last kart standing wins', it: 'Ogni colpo costa HP: vince l\u2019ultimo kart in piedi' },
  'battle.zones': { en: 'Zone Control', it: 'Controllo zone' },
  'battle.zones.d': { en: 'Capture and hold the rings to bank points', it: 'Cattura e difendi gli anelli per accumulare punti' },
  'battle.survival': { en: 'Survival', it: 'Sopravvivenza' },
  'battle.survival.d': { en: 'HP drains over time and from hits - outlast everyone', it: 'Gli HP calano col tempo e con i colpi: resisti pi\u00f9 di tutti' },
  'battle.score': { en: 'Score Battle', it: 'Battaglia a punti' },
  'battle.score.d': { en: '+1 per hit, +2 per KO - most points when time is up wins', it: '+1 per colpo, +2 per KO: il punteggio pi\u00f9 alto vince' },
  'battle.ko': { en: '{name} knocked out!', it: '{name} eliminato!' },
  'battle.win': { en: '{name} wins the battle!', it: '{name} vince la battaglia!' },
  'battle.timeUp': { en: 'TIME UP!', it: 'TEMPO SCADUTO!' },
  'battle.cores': { en: '{cores}/{goal} cores', it: '{cores}/{goal} nuclei' },
  'battle.hp': { en: 'HP', it: 'HP' },
  'arena.emberForge': { en: 'Ember Forge', it: 'Forgia Ardente' },
  'arena.emberForge.desc': { en: 'Flame jets scorch the forge floor', it: 'Getti di fiamma bruciano il pavimento della forgia' },
  'arena.cryoHall': { en: 'Cryo Hall', it: 'Sala di Cristallo' },
  'arena.cryoHall.desc': { en: 'Sliding crystal shards patrol the hall', it: 'Schegge di cristallo scivolano nella sala' },
  'arena.neonPlaza': { en: 'Neon Plaza', it: 'Piazza Neon' },
  'arena.neonPlaza.desc': { en: 'Pendulums sweep the neon square', it: 'Pendoli spazzano la piazza al neon' },
  'arena.skyAtoll': { en: 'Sky Atoll', it: 'Atollo Celeste' },
  'arena.skyAtoll.desc': { en: 'Low gravity - float and strike', it: 'Bassa gravit\u00e0: galleggia e colpisci' },

  // ---------------- progression & achievements ----------------
  'race.boardRank': { en: 'Leaderboard: rank {rank}', it: 'Classifica: posizione {rank}' },
  'progression.xp': { en: '+{xp} XP', it: '+{xp} PE' },
  'progression.levelUp': { en: 'LEVEL {level}!', it: 'LIVELLO {level}!' },
  'progression.unlocked': { en: 'Unlocked: {item}', it: 'Sbloccato: {item}' },
  'achievement.earned': { en: 'Achievement: {name}', it: 'Traguardo: {name}' },

  'ach.firstRace': { en: 'Ignition', it: 'Accensione' },
  'ach.firstRace.d': { en: 'Finish your first race', it: 'Completa la tua prima gara' },
  'ach.firstWin': { en: 'First Flame', it: 'Prima fiamma' },
  'ach.firstWin.d': { en: 'Win a race', it: 'Vinci una gara' },
  'ach.podium10': { en: 'Podium Regular', it: 'Abitu\u00e9 del podio' },
  'ach.podium10.d': { en: 'Finish top 3 ten times', it: 'Arriva nei primi 3 dieci volte' },
  'ach.lap50': { en: 'Lap Collector', it: 'Collezionista di giri' },
  'ach.lap50.d': { en: 'Complete 50 laps', it: 'Completa 50 giri' },
  'ach.fastest5': { en: 'Hot Streak', it: 'Scia rovente' },
  'ach.fastest5.d': { en: 'Set 5 fastest laps', it: 'Firma 5 giri pi\u00f9 veloci' },
  'ach.record1': { en: 'Time Keeper', it: 'Custode del tempo' },
  'ach.record1.d': { en: 'Set a time trial record', it: 'Stabilisci un record a tempo' },
  'ach.record8': { en: 'Record Hunter', it: 'Cacciatore di record' },
  'ach.record8.d': { en: 'Set 8 time trial records', it: 'Stabilisci 8 record a tempo' },
  'ach.cup1': { en: 'Cup Collector', it: 'Collezionista di coppe' },
  'ach.cup1.d': { en: 'Win any cup trophy', it: 'Vinci un trofeo di coppa' },
  'ach.cupGold': { en: 'Golden Hands', it: 'Mani d\u2019oro' },
  'ach.cupGold.d': { en: 'Win a Gold trophy', it: 'Vinci un trofeo d\u2019oro' },
  'ach.cupPlatinum': { en: 'Forge Master', it: 'Maestro della forgia' },
  'ach.cupPlatinum.d': { en: 'Win a Platinum trophy', it: 'Vinci un trofeo di platino' },
  'ach.items20': { en: 'Arsenal', it: 'Arsenale' },
  'ach.items20.d': { en: 'Use 20 power-ups', it: 'Usa 20 potenziamenti' },
  'ach.items30': { en: 'Lucky Crate', it: 'Cassa fortunata' },
  'ach.items30.d': { en: 'Collect 30 power-ups', it: 'Raccogli 30 potenziamenti' },
  'ach.ghost1': { en: 'Ghost Rider', it: 'Cavaliere fantasma' },
  'ach.ghost1.d': { en: 'Race against a ghost', it: 'Gareggia contro un ghost' },
  'ach.explorer': { en: 'Explorer', it: 'Esploratore' },
  'ach.explorer.d': { en: 'Race on all 16 tracks', it: 'Corri su tutte le 16 piste' },
  'ach.level5': { en: 'Rising Star', it: 'Stella nascente' },
  'ach.level5.d': { en: 'Reach level 5', it: 'Raggiungi il livello 5' },
  'ach.level10': { en: 'Sunforged', it: 'Forgiato dal sole' },
  'ach.level10.d': { en: 'Reach level 10', it: 'Raggiungi il livello 10' },
};
