// ============================================================================
// Localized names/descriptions for content (characters, parts, items...).
// Merged into the main dictionary by i18n.js - content keeps its strings
// next to its data. Every key has EN + IT (verified by tests).
// ============================================================================

export const CONTENT_STRINGS = {
  // ---------------- characters ----------------
  'char.ember': { en: 'Ember', it: 'Ember' },
  'char.ember.species': { en: 'the Dustfox', it: 'la Volpe delle Sabbie' },
  'char.ember.personality': { en: 'Balanced daredevil with fire in her tail', it: 'Temeraria equilibrata con il fuoco nella coda' },
  'char.cinder': { en: 'Cinder', it: 'Cinder' },
  'char.cinder.species': { en: 'the Magmabear', it: 'l\u2019Orso di Magma' },
  'char.cinder.personality': { en: 'Heavyweight bruiser, first into every brawl', it: 'Peso massimo aggressivo, sempre primo nella mischia' },
  'char.zephyr': { en: 'Zephyr', it: 'Zephyr' },
  'char.zephyr.species': { en: 'the Windheron', it: 'l\u2019Airone del Vento' },
  'char.zephyr.personality': { en: 'Feather-light and quick off the line', it: 'Leggero come una piuma, scatto bruciante' },
  'char.bastion': { en: 'Bastion', it: 'Bastion' },
  'char.bastion.species': { en: 'the Ironshell', it: 'il Guscio di Ferro' },
  'char.bastion.personality': { en: 'Unmovable wall, shrugs off every hit', it: 'Muro inamovibile, ignora ogni colpo' },
  'char.nova': { en: 'Nova', it: 'Nova' },
  'char.nova.species': { en: 'the Starlynx', it: 'la Lince Stellare' },
  'char.nova.personality': { en: 'Chases pure top speed, fragile but fast', it: 'Insegue la velocit\u00e0 pura, fragile ma velocissima' },
  'char.thistle': { en: 'Thistle', it: 'Thistle' },
  'char.thistle.species': { en: 'the Bramblehop', it: 'il Salto di Rovo' },
  'char.thistle.personality': { en: 'Twitchy corner dancer, impossible to box out', it: 'Danzatore di curve, impossibile da chiudere' },
  'char.coral': { en: 'Coral', it: 'Coral' },
  'char.coral.species': { en: 'the Tidedrake', it: 'il Drago delle Maree' },
  'char.coral.personality': { en: 'At home on any surface, wet or wild', it: 'A suo agio su ogni superficie, bagnata o selvaggia' },
  'char.volt': { en: 'Volt', it: 'Volt' },
  'char.volt.species': { en: 'the Stormkit', it: 'il Cucciolo della Tempesta' },
  'char.volt.personality': { en: 'Explodes off the start, never stops buzzing', it: 'Esplode alla partenza, non smette mai di vibrare' },
  'char.obsidian': { en: 'Obsidian', it: 'Obsidian' },
  'char.obsidian.species': { en: 'the Ashwing', it: 'l\u2019Ala di Cenere' },
  'char.obsidian.personality': { en: 'Drift artist from the dark side of the caldera', it: 'Artista della derapata dal lato buio del cratere' },
  'char.juniper': { en: 'Juniper', it: 'Juniper' },
  'char.juniper.species': { en: 'the Mosscat', it: 'il Gatto di Muschio' },
  'char.juniper.personality': { en: 'Forest wanderer, treats dirt like tarmac', it: 'Nomade della foresta, tratta lo sterrato come asfalto' },
  'char.ratchet': { en: 'Ratchet', it: 'Ratchet' },
  'char.ratchet.species': { en: 'the Scraprat', it: 'il Ratto di Rottami' },
  'char.ratchet.personality': { en: 'Grease-stained tinkerer with a heavy wrench', it: 'Meccanico unto con una chiave pesante' },
  'char.lumi': { en: 'Lumi', it: 'Lumi' },
  'char.lumi.species': { en: 'the Frostowl', it: 'il Gufo di Gelo' },
  'char.lumi.personality': { en: 'Calm, precise, slices corners like ice', it: 'Calmo, preciso, taglia le curve come ghiaccio' },
  'char.aurelia': { en: 'Aurelia', it: 'Aurelia' },
  'char.aurelia.species': { en: 'the Sundancer', it: 'la Danzatrice del Sole' },
  'char.aurelia.personality': { en: 'Golden champion of the Crown Circuit', it: 'Campionessa dorata del Circuito della Corona' },
  'char.umbra': { en: 'Umbra', it: 'Umbra' },
  'char.umbra.species': { en: 'the Voidmole', it: 'la Talpa del Vuoto' },
  'char.umbra.personality': { en: 'Digs through shortcuts nobody else can see', it: 'Scava scorciatoie che nessun altro riesce a vedere' },
  'unlock.aurelia': { en: 'Win the Crown Cup', it: 'Vinci la Coppa Corona' },
  'unlock.umbra': { en: 'Complete the Night Shift achievement', it: 'Completa l\u2019impresa Turno di Notte' },

  // ---------------- chassis ----------------
  'chassis.duneBlazer': { en: 'Dune Blazer MK-1', it: 'Dune Blazer MK-1' },
  'chassis.duneBlazer.desc': { en: 'The trusty all-rounder from the Sunforge garage.', it: 'L\u2019affidabile tuttofare dell\u2019officina Sunforge.' },
  'chassis.featherwing': { en: 'Featherwing', it: 'Ala di Piuma' },
  'chassis.featherwing.desc': { en: 'So light it leaps. Gives up top speed for zip.', it: 'Cos\u00ec leggero che vola. Rinuncia alla velocit\u00e0 per lo scatto.' },
  'chassis.ironcladHauler': { en: 'Ironclad Hauler', it: 'Corazzato da Traino' },
  'chassis.ironcladHauler.desc': { en: 'A rolling fortress. Slow to wake, hard to stop.', it: 'Una fortezza su ruote. Lento a svegliarsi, difficile da fermare.' },
  'chassis.tempestBolt': { en: 'Tempest Bolt', it: 'Fulmine Tempesta' },
  'chassis.tempestBolt.desc': { en: 'Built for screaming straights. Nervous in corners.', it: 'Fatto per rettilinei urlanti. Nervoso in curva.' },
  'chassis.bumblewisp': { en: 'Bumblewisp', it: 'Soffio di Calabrone' },
  'chassis.bumblewisp.desc': { en: 'A corner-hugging honeybee. Slower on the open road.', it: 'Un\u2019ape che abbraccia le curve. Pi\u00f9 lento sul dritto.' },
  'chassis.rockjaw': { en: 'Rockjaw', it: 'Mascella di Roccia' },
  'chassis.rockjaw.desc': { en: 'Eats rough terrain for breakfast. Heavy and blunt.', it: 'Divora terreni accidentati a colazione. Pesante e diretto.' },
  'chassis.cometCourier': { en: 'Comet Courier', it: 'Corriere Cometa' },
  'chassis.cometCourier.desc': { en: 'Launches like a comet, slides wide if you blink.', it: 'Parte come una cometa, allarga la traiettoria se sbatti le palpebre.' },
  'chassis.gearworkRoyale': { en: 'Gearwork Royale', it: 'Ingranaggio Reale' },
  'chassis.gearworkRoyale.desc': { en: 'Ancient gear-tech tuned for silky drifts.', it: 'Antica tecnologia a ingranaggi per derapate setose.' },

  // ---------------- wheels ----------------
  'wheel.standard': { en: 'Standard Treads', it: 'Cingoli Standard' },
  'wheel.slimline': { en: 'Slimline Racers', it: 'Cerchi Filanti' },
  'wheel.duneRollers': { en: 'Dune Rollers', it: 'Rulli delle Dune' },
  'wheel.gyroRings': { en: 'Gyro Rings', it: 'Anelli Giroscopici' },
  'wheel.ironDrums': { en: 'Iron Drums', it: 'Tamburi di Ferro' },
  'wheel.slickComets': { en: 'Slick Comets', it: 'Comete Slick' },
  'wheel.stormSpikes': { en: 'Storm Spikes', it: 'Punte della Tempesta' },
  'wheel.chromeHalos': { en: 'Chrome Halos', it: 'Aure Cromate' },
  'wheel.mossGrippers': { en: 'Moss Grippers', it: 'Aderenti di Muschio' },
  'wheel.turboSprockets': { en: 'Turbo Sprockets', it: 'Ruote Dentate Turbo' },
  'wheel.balloonFloaters': { en: 'Balloon Floaters', it: 'Palloni Galleggianti' },
  'wheel.rallyHex': { en: 'Rally Hex', it: 'Esagonali da Rally' },

  // ---------------- cosmetics ----------------
  'paint.sunsetOrange': { en: 'Sunset Orange', it: 'Arancio Tramonto' },
  'paint.duneTeal': { en: 'Dune Teal', it: 'Verde Acqua Duna' },
  'paint.emberRed': { en: 'Ember Red', it: 'Rosso Brace' },
  'paint.canyonCream': { en: 'Canyon Cream', it: 'Crema del Canyon' },
  'paint.nightInk': { en: 'Night Ink', it: 'Inchiostro Notturno' },
  'paint.forestMoss': { en: 'Forest Moss', it: 'Muschio di Foresta' },
  'paint.royalViolet': { en: 'Royal Violet', it: 'Viola Reale' },
  'paint.stormYellow': { en: 'Storm Yellow', it: 'Giallo Tempesta' },
  'paint.glacierBlue': { en: 'Glacier Blue', it: 'Blu Ghiacciaio' },
  'paint.magmaBlack': { en: 'Magma Black', it: 'Nero Magma' },
  'paint.coralPink': { en: 'Coral Pink', it: 'Rosa Corallo' },
  'paint.bronzeGear': { en: 'Bronze Gear', it: 'Bronzo Ingranaggio' },
  'paint.silverMist': { en: 'Silver Mist', it: 'Nebbia d\u2019Argento' },
  'paint.goldForge': { en: 'Gold Forge', it: 'Oro della Forgia' },
  'paint.prismPearl': { en: 'Prism Pearl', it: 'Perla Prisma' },
  'paint.voidChrome': { en: 'Void Chrome', it: 'Cromo del Vuoto' },

  'decal.none': { en: 'Clean', it: 'Pulito' },
  'decal.racingStripe': { en: 'Racing Stripe', it: 'Striscia da Corsa' },
  'decal.sunEmblem': { en: 'Sun Emblem', it: 'Emblema Solare' },
  'decal.gearStamp': { en: 'Gear Stamp', it: 'Stampo a Ingranaggio' },
  'decal.flameTrail': { en: 'Flame Trail', it: 'Scia di Fiamme' },
  'decal.stormBolt': { en: 'Storm Bolt', it: 'Fulmine Tempesta' },
  'decal.waveCrest': { en: 'Wave Crest', it: 'Cresta d\u2019Onda' },
  'decal.starField': { en: 'Star Field', it: 'Campo Stellato' },

  'exhaust.twinPipes': { en: 'Twin Pipes', it: 'Doppio Scarico' },
  'exhaust.stackVents': { en: 'Stack Vents', it: 'Sfiati Verticali' },
  'exhaust.quadBurst': { en: 'Quad Burst', it: 'Quadruplo Scoppio' },
  'exhaust.turbineRing': { en: 'Turbine Ring', it: 'Anello Turbina' },

  'effect.classicFlame': { en: 'Classic Flame', it: 'Fiamma Classica' },
  'effect.emberTrail': { en: 'Ember Trail', it: 'Scia di Braci' },
  'effect.frostWake': { en: 'Frost Wake', it: 'Scia Gelata' },
  'effect.venomSpark': { en: 'Venom Spark', it: 'Scintilla Velenosa' },
  'effect.voidShimmer': { en: 'Void Shimmer', it: 'Bagliore del Vuoto' },

  // ---------------- items (22 originals) ----------------
  'item.fluxBolt': { en: 'Flux Bolt', it: 'Dardo di Flusso' },
  'item.fluxBolt.desc': { en: 'Homing bolt that locks onto engine heat ahead of you.', it: 'Dardo a ricerca che aggancia il calore del motore davanti a te.' },
  'item.fluxBolt.counter': { en: 'Drift hard to break the lock.', it: 'Derapata decisa per rompere l\u2019aggancio.' },
  'item.gravityAnchor': { en: 'Gravity Anchor', it: 'Ancora Gravitazionale' },
  'item.gravityAnchor.desc': { en: 'Pins the kart ahead to the road: no hops, no drifts, less speed.', it: 'Inchioda il kart davanti all\u2019asfalto: niente salti, niente derapate, meno velocit\u00e0.' },
  'item.gravityAnchor.counter': { en: 'Cleanse with a Pulse Ring or block with a shield.', it: 'Rimuovi con Anello Pulsante o blocca con uno scudo.' },
  'item.mirageClone': { en: 'Mirage Clone', it: 'Clone Miraggio' },
  'item.mirageClone.desc': { en: 'Drops a hologram behind you that eats one hit and flashes.', it: 'Lascia un ologramma dietro di te che assorbe un colpo e abbaglia.' },
  'item.mirageClone.counter': { en: 'Clones shimmer - shoot the real kart instead.', it: 'I cloni tremolano: colpisci il kart vero.' },
  'item.pulseRing': { en: 'Pulse Ring', it: 'Anello Pulsante' },
  'item.pulseRing.desc': { en: 'A wave that erases nearby hazards and cleanses your debuffs.', it: 'Un\u2019onda che cancella i pericoli vicini e rimuove i tuoi malus.' },
  'item.pulseRing.counter': { en: 'Short radius - timing matters.', it: 'Raggio corto: il tempismo conta.' },
  'item.overdriveCore': { en: 'Overdrive Core', it: 'Nucleo Fuorigiri' },
  'item.overdriveCore.desc': { en: 'Violent burst of speed, but your steering goes twitchy and drifts die.', it: 'Esplosione di velocit\u00e0, ma lo sterzo diventa nervoso e le derapate spariscono.' },
  'item.overdriveCore.counter': { en: 'Its own drawback is the counterplay.', it: 'Il suo difetto \u00e8 la contromossa.' },
  'item.vortexMine': { en: 'Vortex Mine', it: 'Mina Vortice' },
  'item.vortexMine.desc': { en: 'Dropped mine that drags karts in, then launches them skyward.', it: 'Mina che trascina i kart verso di s\u00e9 e li lancia in aria.' },
  'item.vortexMine.counter': { en: 'Visible and avoidable - take the wide line.', it: 'Visibile ed evitabile: allarga la traiettoria.' },
  'item.phaseShield': { en: 'Phase Shield', it: 'Scudo di Fase' },
  'item.phaseShield.desc': { en: 'Slip through karts and hazards for 4s - but you can\u2019t grab items.', it: 'Attraversa kart e pericoli per 4s, ma niente oggetti.' },
  'item.phaseShield.counter': { en: 'You can\u2019t attack or collect while phased.', it: 'In fase non puoi attaccare n\u00e9 raccogliere.' },
  'item.timeRipple': { en: 'Time Ripple', it: 'Increspatura Temporale' },
  'item.timeRipple.desc': { en: 'A bubble that slows every rival inside it. You are exempt.', it: 'Una bolla che rallenta ogni rivale al suo interno. Tu sei escluso.' },
  'item.timeRipple.counter': { en: 'Audible windup - sprint out of the radius.', it: 'Carica udibile: esci dal raggio.' },
  'item.magnetSurge': { en: 'Magnet Surge', it: 'Scarica Magnetica' },
  'item.magnetSurge.desc': { en: 'Item boxes fly toward you for a few seconds.', it: 'Le casse oggetto volano verso di te per qualche secondo.' },
  'item.magnetSurge.counter': { en: 'Only helps near boxes.', it: 'Utile solo vicino alle casse.' },
  'item.repairDrone': { en: 'Repair Drone', it: 'Drone Riparatore' },
  'item.repairDrone.desc': { en: 'Cleanses debuffs, patches on a shield charge and a little boost.', it: 'Rimuove i malus, aggiunge una carica scudo e un po\u2019 di boost.' },
  'item.repairDrone.counter': { en: 'Reactive, not proactive.', it: 'Reattivo, non proattivo.' },
  'item.echoSnare': { en: 'Echo Snare', it: 'Laccio Eco' },
  'item.echoSnare.desc': { en: 'Wraps the target\u2019s steering in echoes - it reverses briefly.', it: 'Avvolge lo sterzo del bersaglio in echi: si inverte per un istante.' },
  'item.echoSnare.counter': { en: 'Release a drift to snap out of it faster.', it: 'Rilascia una derapata per liberarti prima.' },
  'item.prismWall': { en: 'Prism Wall', it: 'Muro Prisma' },
  'item.prismWall.desc': { en: 'A glass wall behind you: anyone crossing it is badly slowed.', it: 'Un muro di vetro dietro di te: chi lo attraversa rallenta di colpo.' },
  'item.prismWall.counter': { en: 'Narrow - go around it.', it: 'Stretto: aggiralo.' },
  'item.slipstreamHarpoon': { en: 'Slipstream Harpoon', it: 'Arpione di Scia' },
  'item.slipstreamHarpoon.desc': { en: 'Hook the kart ahead and get yanked toward it.', it: 'Aggancia il kart davanti e fatti trascinare verso di lui.' },
  'item.slipstreamHarpoon.counter': { en: 'The target breaks free by boosting.', it: 'Il bersaglio si libera con un boost.' },
  'item.staticBloom': { en: 'Static Bloom', it: 'Fiore Statico' },
  'item.staticBloom.desc': { en: 'Thrown seed that blooms into a field killing drift charge.', it: 'Seme lanciato che fiorisce in un campo che azzera la carica derapata.' },
  'item.staticBloom.counter': { en: 'Clearly visible - steer around the petals.', it: 'Ben visibile: sterza attorno ai petali.' },
  'item.chronoShard': { en: 'Chrono Shard', it: 'Scheggia Crono' },
  'item.chronoShard.desc': { en: 'Snapshots your speed; if you get slowed hard, it snaps you back.', it: 'Fotografa la tua velocit\u00e0; se rallenti di colpo, ti ci riporta.' },
  'item.chronoShard.counter': { en: 'Single use, timing is everything.', it: 'Uso singolo: il tempismo \u00e8 tutto.' },
  'item.ionLash': { en: 'Ion Lash', it: 'Frusta Ionica' },
  'item.ionLash.desc': { en: 'Front arc whip: knocks rivals sideways and steals their charge.', it: 'Frusta ad arco frontale: sposta i rivali e ruba la loro carica.' },
  'item.ionLash.counter': { en: 'Very short range.', it: 'Portata brevissima.' },
  'item.decoyBeacon': { en: 'Decoy Beacon', it: 'Faro Esca' },
  'item.decoyBeacon.desc': { en: 'Thrown beacon that retargets enemy projectiles to itself.', it: 'Faro lanciato che devia su di s\u00e9 i proiettili nemici.' },
  'item.decoyBeacon.counter': { en: 'Only fools projectiles.', it: 'Inganna solo i proiettili.' },
  'item.gravitonWell': { en: 'Graviton Well', it: 'Pozzo Gravitonico' },
  'item.gravitonWell.desc': { en: 'A pocket of heavy gravity that bends rivals off their line.', it: 'Una sacca di gravit\u00e0 pesante che piega i rivali fuori linea.' },
  'item.gravitonWell.counter': { en: 'Wide and visible - give it room.', it: 'Ampio e visibile: dagli spazio.' },
  'item.tempestCell': { en: 'Tempest Cell', it: 'Cella Tempesta' },
  'item.tempestCell.desc': { en: 'Your next 3 drift boosts zap rivals right behind you.', it: 'I prossimi 3 boost di derapata fulminano chi ti segue.' },
  'item.tempestCell.counter': { en: 'Requires drifting; zaps only behind.', it: 'Richiede derapate; colpisce solo dietro.' },
  'item.nanoSwarm': { en: 'Nano Swarm', it: 'Sciame Nano' },
  'item.nanoSwarm.desc': { en: 'A cone of gnats behind you that drags anyone who flies into it.', it: 'Un cono di zanzare dietro di te che frena chi ci vola dentro.' },
  'item.nanoSwarm.counter': { en: 'Pass on the other side.', it: 'Supera dall\u2019altro lato.' },
  'item.auroraVeil': { en: 'Aurora Veil', it: 'Velo d\u2019Aurora' },
  'item.auroraVeil.desc': { en: 'A shimmering ribbon that makes it icy-slippery to cross.', it: 'Un nastro cangiante che diventa ghiaccio scivoloso al passaggio.' },
  'item.auroraVeil.counter': { en: 'Avoid the ribbon.', it: 'Evita il nastro.' },
  'item.kineticSiphon': { en: 'Kinetic Siphon', it: 'Sifone Cinetico' },
  'item.kineticSiphon.desc': { en: 'Drains a little speed from the kart ahead and feeds it to you.', it: 'Aspira un po\u2019 di velocit\u00e0 dal kart davanti e la d\u00e0 a te.' },
  'item.kineticSiphon.counter': { en: 'Break line of sight or boost away.', it: 'Rompi la linea di vista o scappa col boost.' },

  // ---------------- HUD / race (new) ----------------
  'hud.item': { en: 'ITEM', it: 'OGGETTO' },
  'hud.itemHint': { en: 'Press E to use', it: 'Premi E per usare' },
  'race.gotItem': { en: 'Got {item}!', it: 'Ottenuto: {item}!' },
  'race.hitBy': { en: 'Hit by {item}!', it: 'Colpito da {item}!' },
  'race.youHit': { en: '{victim} hit!', it: '{victim} colpito!' },
  'race.itemBlocked': { en: 'Shield absorbed the hit!', it: 'Lo scudo ha assorbito il colpo!' },
  'race.chronoRestore': { en: 'Chrono restore!', it: 'Ripristino Crono!' },
  'race.newBestTotal': { en: 'New best total time!', it: 'Nuovo miglior tempo totale!' },
  'race.newRecord': { en: 'NEW RECORD!', it: 'NUOVO RECORD!' },
  'race.ghostSaved': { en: 'Ghost saved', it: 'Ghost salvato' },
  'race.racingGhost': { en: 'Racing your ghost', it: 'Sfida il tuo ghost' },

  // ---------------- settings (new) ----------------
  'settings.items': { en: 'Power-ups', it: 'Potenziamenti' },
  'settings.music': { en: 'Music volume', it: 'Volume musica' },
  'settings.on': { en: 'On', it: 'On' },
  'settings.off': { en: 'Off', it: 'Off' },

  // ---------------- controls ----------------
  'controls.help': { en: 'WASD / Arrows drive · SHIFT drift · SPACE trick · E item · R reset · ESC pause',
                     it: 'WASD / Frecce guida · SHIFT derapata · SPACE acrobazia · E oggetto · R reset · ESC pausa' },
};
